import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'fr' | 'de' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('es');

  // Load saved language from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('thaii-language') as Language;
    if (savedLanguage && ['es', 'en', 'fr', 'de', 'ru'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('thaii-language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translations object
const translations = {
  es: {
    // Header
    'cart': 'Carrito',
    'phone': '951 40 19 37',
    'address': 'Plaza de la Solidaridad, 9 - Málaga',
    
    // Hero
    'prepare_to_taste': 'PREPÁRALO',
    'to_your_liking': 'AL GUSTO',
    'choose_what_you_like': 'Elige tu plato favorito y...',
    'take_it_home': '¡llévátelo a casa!',
    'order_online': 'HACER PEDIDO ONLINE',
     'call_us': 'LLAMAR: 951 40 19 37',
     
     // Auth
     'auth_title': 'Iniciar Sesión en Thaii Express',
     'login': 'Iniciar Sesión',
     'signup': 'Registrarse',
     'email': 'Correo Electrónico',
     'password': 'Contraseña',
     'loading': 'Cargando...',
     'login_success': '¡Inicio de Sesión Exitoso!',
     'signup_success': '¡Cuenta Creada!',
     'check_email_confirmation': 'Por favor revisa tu correo para confirmar tu cuenta.',
     'logout': 'Cerrar Sesión',
     'myOrders': 'Mis Pedidos',
     
     // Main Categories
    'entrantes': 'Entrantes',
    'arroz': 'Arroz', 
    'tallarines': 'Tallarines',
    'sopas': 'Sopas',
    'pokes': 'Pokes',
    'postres': 'Postres',
    'ensaladas': 'Ensaladas',
    'otras': 'Otras del Mundo',
    'bebidas': 'Bebidas',
    
    // Proteins
    'chicken': 'Pollo',
    'beef': 'Ternera', 
    'pork': 'Cerdo',
    'shrimp': 'Gambas',
    'vegetables': 'Verduras',
    'select_protein': 'Selecciona tu proteína',
    'protein_tab': 'Proteína',
    
    // Sauces
    'teriyaki': 'Teriyaki',
    'sweet_sour': 'Agridulce',
    'curry_sauce': 'Curry',
    'soy_sauce': 'Soja',
    'spicy_sauce': 'Picante',
    'select_sauce': 'Selecciona tu salsa',
    'sauce_tab': 'Salsa',
    'spicy_level': 'Nivel de picante',
    
    // Rice Customizer
    'rice_customizer_title': 'Personaliza tu Arroz',
    'rice_customizer_description': 'Selecciona tu proteína y salsa favorita para crear tu plato perfecto',
    'customize_rice': 'Personaliza tu arroz',
    'selected_items': 'Elementos seleccionados',
    
    // Subcategories
    'classic': 'Classic',
    'yellow_curry': 'Curry Amarillo',
    'green_curry': 'Curry Verde',
    'red_curry': 'Curry Rojo',
    
    // Common
    'price': 'Precio',
    'add_to_cart': 'Añadir al carrito',
    'vegetarian': 'Vegetariano',
    'spicy': 'Picante',
    
    // Cart
    'your_cart': 'Tu carrito',
    'empty_cart': 'Tu carrito está vacío',
    'quantity': 'Cantidad',
    'remove': 'Eliminar',
    'subtotal': 'Subtotal',
    'delivery_fee': 'Gastos de envío',
    'total': 'Total',
    'customer_info': 'Información del cliente',
    'name': 'Nombre',
    'phone_number': 'Teléfono',
    'address_full': 'Dirección completa',
    'notes': 'Notas (opcional)',
    'send_order_whatsapp': 'ENVIAR PEDIDO POR WHATSAPP',
    
    // Dialog
    'doubts_about_dishes': '¿Tienes dudas sobre nuestros platos?',
    'khopi_greeting': '¡Hola! Soy Khopi, la mascota de Thaii Express. Si tienes dudas sobre los ingredientes de algún plato o necesitas ayuda para elegir, ¡llámanos!',
    'see_full_menu': 'VER MENÚ COMPLETO',
    
    // Footer
    'restaurant_description': 'Comida asiática auténtica para llevar. Prepáralo al gusto y llévátelo a casa.',
    'contact_title': 'CONTACTO',
    'hours_title': 'HORARIOS',
    'monday_sunday': 'Lunes - Domingo',
    'hours_time': '12:00 - 23:00',
    'online_orders_available': 'Pedidos online disponibles durante todo el horario de apertura',
    'all_rights_reserved': '© 2024 Thaii Express Málaga. Todos los derechos reservados.',
    'top_sales': 'Lo más vendido',
    
    // Loading and Error states
    'loading_products': 'Cargando productos...',
    'error_loading': 'Error',
    'retry': 'Reintentar',
    'coming_soon': 'Próximamente disponible...',
    
    // Category descriptions
    'starters_description': 'Deliciosos entrantes para comenzar tu experiencia culinaria',
    'noodles_description': 'Tallarines tradicionales asiáticos salteados con verduras frescas',
    'soups_description': 'Sopas reconfortantes con sabores auténticos de la cocina asiática',
    'pokes_description': 'Pokes frescos y saludables con ingredientes de calidad',
    'desserts_description': 'Deliciosos postres para endulzar tu experiencia',
    'salads_description': 'Ensaladas frescas y nutritivas con ingredientes de temporada',
    'drinks_description': 'Refrescantes bebidas para acompañar tu comida',
    
    // Rice Customizer Proteins
    'chicken_protein': 'Pollo',
    'beef_protein': 'Ternera',
    'shrimp_protein': 'Gambas',
    'chicken_beef': 'Pollo y Ternera',
    'chicken_shrimp': 'Pollo y Gambas',
    'beef_shrimp': 'Ternera y Gambas',
    'mix_three': 'Pollo, Ternera y Gambas',
    
    // Rice Customizer Protein Descriptions
    'chicken_desc': 'Tierno pollo marinado',
    'beef_desc': 'Jugosa ternera salteada',
    'shrimp_desc': 'Gambas frescas del mar',
    'chicken_beef_desc': 'Combinación de pollo y ternera',
    'chicken_shrimp_desc': 'Pollo con gambas frescas',
    'beef_shrimp_desc': 'Ternera con gambas del mar',
    'mix_three_desc': 'Combinación completa de proteínas',
    
    // Rice Customizer Sauces
    'classic_sauce': 'Salsa Classic',
    'original_sauce': 'Salsa Original',
    'teriyaki_sauce': 'Salsa Teriyaki',
    'yellow_curry_sauce': 'Curry Amarillo',
    'green_curry_sauce': 'Curry Verde',
    'red_curry_sauce': 'Curry Rojo',
    
    // Rice Customizer Sauce Descriptions
    'classic_sauce_desc': 'Salsa tradicional asiática',
    'original_sauce_desc': 'Nuestra receta especial',
    'teriyaki_sauce_desc': 'Dulce y sabrosa salsa japonesa',
    'yellow_curry_sauce_desc': 'Suave curry amarillo',
    'green_curry_sauce_desc': 'Curry verde medio picante',
    'red_curry_sauce_desc': 'Intenso curry rojo picante',
    
    // Spicy levels
    'medium_spicy': 'Medio picante',
    'spicy_level_high': 'Picante',
    
    // Custom rice creation
    'custom_rice_with': 'Arroz frito con',
    'custom_rice_and': 'y',
    'custom_rice_desc': 'Arroz frito personalizado con',

    // Noodle types
    'noodle_finos': 'Finos (Noodles)',
    'noodle_anchos': 'Anchos (Pad Thai)',
    'noodle_glass': 'Glass',
    'noodle_udon': 'Udon',
    'noodle_finos_desc': 'Tallarines finos tradicionales',
    'noodle_anchos_desc': 'Tallarines anchos estilo Pad Thai',
    'noodle_glass_desc': 'Tallarines transparentes de habas',
    'noodle_udon_desc': 'Tallarines gruesos japoneses',

    // Noodle customizer
    'noodle_customizer_title': 'PERSONALIZA TUS TALLARINES',
    'noodle_customizer_description': 'Elige el tipo de tallarín, tu proteína favorita y la salsa perfecta',
    'step_noodle_type': 'Tipo de Tallarín',
    'step_protein': 'Proteína',
    'step_sauce': 'Salsa',
    'noodle_type': 'Tipo de tallarín',
    'custom_noodles_with': 'Tallarines personalizados con',
    'custom_noodles_and': 'y',
    'custom_noodles_desc': 'Tallarines salteados al wok con',
    'custom_noodles_with_sauce': 'con salsa',
    'order_summary': 'Resumen del pedido',
    'protein': 'Proteína',
    'sauce': 'Salsa',
    
    // Extra vegetables
    'extra_vegetables': 'Verduras Adicionales',
    'extra_vegetables_optional': 'Verduras Adicionales (Opcional)',
    'extra_vegetables_desc': 'Selecciona las verduras extra que desees añadir a tu plato',
    'extra_vegetables_label': 'Verduras extra',
    'step_vegetables': 'Verduras Extra',
    
    // Vegetable names
    'veg_egg': 'Huevo',
    'veg_cilantro': 'Cilantro',
    'veg_basil': 'Albahaca',
    'veg_bean_sprouts': 'Brotes de Soja',
    'veg_red_onion': 'Cebolla roja',
    'veg_corn': 'Maíz',
    'veg_green_beans': 'Judía Verde',
    'veg_carrot': 'Zanahoria',
    'veg_peanut': 'Cacahuete',
    'veg_broccoli': 'Brócoli',
    'veg_scallion': 'Cebolleta',
    'veg_mushroom': 'Champiñones',
    'veg_pepper': 'Pimiento',

    // Enhanced protein translations
    'protein_chicken': 'Pollo',
    'protein_beef': 'Ternera',
    'protein_shrimp': 'Gambas',
    'protein_chicken_desc': 'Pechuga de pollo fresca y tierna',
    'protein_beef_desc': 'Tierna ternera de primera calidad',
    'protein_shrimp_desc': 'Gambas frescas del mar',
    'protein_chicken_beef': 'Pollo y Ternera',
    'protein_chicken_shrimp': 'Pollo y Gambas',
    'protein_beef_shrimp': 'Ternera y Gambas',
    'protein_chicken_beef_shrimp': 'Pollo, Ternera y Gambas',
    'protein_chicken_beef_desc': 'Combinación perfecta de pollo y ternera',
    'protein_chicken_shrimp_desc': 'Deliciosa mezcla de pollo y gambas',
    'protein_beef_shrimp_desc': 'Exquisita combinación de ternera y gambas',
    'protein_chicken_beef_shrimp_desc': 'Triple proteína: pollo, ternera y gambas',

    // Enhanced sauce translations
    'sauce_classic': 'Classic',
    'sauce_original': 'Original',
    'sauce_teriyaki': 'Teriyaki',
    'sauce_classic_desc': 'Salsa soja y ostras',
    'sauce_original_desc': 'Cilantro, brotes de soja, zanahoria, cacahuete, salsa tamarindo y lima',
    'sauce_teriyaki_desc': 'Salsa teriyaki tradicional',
    
    // Entrantes translations - Spanish (names and descriptions)
    'panko_chicken': 'Panko pollo (5 unidades)',
    'panko_chicken_desc': 'Crujientes trozos de pollo empanados en panko japonés',
    'panko_shrimp': 'Panko langostino (5 unidades)',
    'panko_shrimp_desc': 'Langostinos empanados en panko crujiente',
    'chicken_skewer_1': 'Pinchito de pollo (1 unidad)',
    'chicken_skewer_1_desc': 'Pincho de pollo marinado a la plancha',
    'chicken_skewer_2': 'Pinchito de pollo (2 unidades)',
    'chicken_skewer_2_desc': 'Dos pinchos de pollo marinado a la plancha',
    'shrimp_skewer_1': 'Pinchito de langostino (1 unidad)',
    'shrimp_skewer_1_desc': 'Pincho de langostino fresco a la plancha',
    'shrimp_skewer_2': 'Pinchito de langostino (2 unidades)',
    'shrimp_skewer_2_desc': 'Dos pinchos de langostino fresco a la plancha',
    'mushroom_skewer_1': 'Pinchito de champiñones (1 unidad)',
    'mushroom_skewer_1_desc': 'Pincho de champiñones frescos a la plancha',
    'mushroom_skewer_2': 'Pinchito de champiñones (2 unidades)',
    'mushroom_skewer_2_desc': 'Dos pinchos de champiñones frescos a la plancha',
    'grilled_salmon': 'Salmón a la plancha',
    'grilled_salmon_desc': 'Filete de salmón fresco a la plancha',
    'spring_rolls': 'Rollito de primavera (2 unidades)',
    'spring_rolls_desc': 'Rollitos crujientes rellenos de verduras frescas',
    'shrimp_rolls': 'Rollito de gambas (8 unidades)',
    'shrimp_rolls_desc': 'Rollitos crujientes rellenos de gambas frescas',
    'chicken_wings': 'Alitas (6 unidades)',
    'chicken_wings_desc': 'Alitas de pollo marinadas y especiadas',
    'gyoza_fried': 'Gyozas con gambas fritas (6 unidades)',
    'gyoza_fried_desc': 'Empanadillas japonesas rellenas de gambas, preparadas fritas',
    'gyoza_grilled': 'Gyozas con gambas plancha (6 unidades)',
    'gyoza_grilled_desc': 'Empanadillas japonesas rellenas de gambas, preparadas a la plancha',
    'bao_chicken': 'Bao Pollo (2 unidades)',
    'bao_chicken_desc': 'Pan al vapor asiático relleno de pollo tierno',
    'bao_shrimp': 'Bao Langostinos (2 unidades)',
    'bao_shrimp_desc': 'Pan al vapor asiático relleno de langostinos frescos',
    'edamame': 'Edamame',
    'edamame_desc': 'Vainas de soja hervidas con sal marina',
    'edamame_spicy': 'Edamame picante',
    'edamame_spicy_desc': 'Vainas de soja hervidas con especias picantes',

    // Soup Customizer
    'soup_customizer_title': 'Personaliza tu Sopa',
    'soup_customizer_description': 'Elige tu tipo de sopa favorita y la proteína que más te guste',
    'step_soup_type': 'Elige tu tipo de sopa',
    'soup_type': 'Tipo de sopa',
    'soup_miso': 'Sopa Miso',
    'soup_miso_desc': 'Tofu, Wakame, Cebolleta y salsa de mariscos',
    'soup_tom_yam': 'Sopa Tom Yam',
    'soup_tom_yam_desc': 'Champiñones, zanahoria, brócoli, tomates cherry, salsa de marisco, medio picante',
    'custom_soup_with': 'Sopa personalizada con',
    'custom_soup_desc': 'y tus ingredientes favoritos',
    'prawn': 'Langostino',
    'veggie': 'Veggie',

    // Poke customizer
    'poke_customizer_title': 'Personaliza tu Poke',
    'poke_customizer_description': 'Elige tu poke bowl favorito con ingredientes frescos',
    'step_poke_type': 'Tipo de Poke',
    'choose_your_poke': 'Selecciona tu poke preferido',
    'poke_type': 'Tipo de Poke',
    'selected': 'Seleccionado',

    // Poke products
    'poke_korean_name': 'Poke Coreano',
    'poke_korean_desc': 'Base de arroz japonés avinagrado con salsa soja, Pollo Crispy, Kimchi, Kiwi, Tofu, langostino, alga, cebolla frita, sésamo, salsa soja y salsa kimchi',
    'poke_japanese_name': 'Poke Japonés', 
    'poke_japanese_desc': 'Base de arroz japonés avinagrado con salsa soja, Wakame, aguacate, sésamo, Tomates cherry, kiwi, Salmón, gambas, salsa japonesa y salsa soja',
    'poke_indonesia_name': 'Poke Indonesia',
    'poke_indonesia_desc': 'Base de arroz japonés avinagrado con salsa soja, Aguacate, sésamo, mango, piña, kiwi, Tomates cherry, pepino, salsa soja y salsa fruta',
    'poke_thailand_name': 'Poke Thailandia',
    'poke_thailand_desc': 'Base de arroz japonés avinagrado con salsa soja, Aguacate, piña, kiwi, gambas, sésamo, cebolla frita, pollo, salsa pimienta y salsa de fruta',
    'poke_basic_name': 'Poke Básico',
    'poke_basic_desc': 'Elección al gusto, elige 150gr de pollo o 2 pollo Crispy, Sésamo y 3 verduras/frutas a elegir entre (wakame, kimchi, tofu, alga, pepino, aguacate, kiwi, tomates cherry, piña, fresa, mango), además tendrá que elegir una de nuestras salsas (Kimchi, soja, Rosa, fruta, Japonesa, César, agridulce)',
    'poke_premium_name': 'Poke Premium',
    'poke_premium_desc': 'Elección al gusto, elige 100gr de Salmón o 150gr de pollo o 2 pollo Crispy, Sésamo y gambas, además deberá elegir 4 verduras/frutas a elegir entre (wakame, kimchi, tofu, alga, pepino, aguacate, kiwi, tomates cherry, piña, fresa, mango), además tendrá que elegir una de nuestras salsas (Kimchi, soja, Rosa, fruta, Japonesa, César, agridulce)',
    
    // Salad Customizer
    'salad_customizer_title': 'PERSONALIZA TU ENSALADA',
    'salad_customizer_description': 'Elige tu ensalada favorita y la proteína que prefieras',
    'step_salad_type': 'Tipo de Ensalada',
    'salad_type': 'Tipo de ensalada',
    
    // Salad types
    'salad_cesar': 'Ensalada César',
    'salad_cesar_ingredients': 'Lechuga, parmesano, aguacate, tomate, picatostes, salsas vinagreta y césar',
    'salad_classic_name': 'Ensalada Classic',
    'salad_classic_ingredients': 'Lechuga, parmesano, aguacate, tomates cherry, pepino, cebolla roja, picatostes, salsas vinagreta y césar',
    
     'salad_malaysia': 'Ensalada Malaysia',
    'salad_malaysia_ingredients': 'Lechuga, pepino, picatostes, tomates cherry, nueces, salsas césar y vinagreta y verduras al wok',
    'salad_thai': 'Ensalada Thailandesa',
    'salad_thai_ingredients': 'Lechuga, tomates cherry, cacahuete, chili, pepino, menta, albahaca, salsas vinagreta y césar, ternera al wok',
    'salad_crispy': 'Ensalada Crispy',
    'salad_crispy_ingredients': 'Lechuga, zanahorias, brotes de soja, tomates cherry, salsas vinagreta y rosa picante, panko pollo o panko langostinos a elegir',
    'salad_fruit': 'Ensalada de Fruta',
    'salad_fruit_ingredients': 'Lechuga, aguacate, tomates cherry, mango, kiwi, fresa y salsa fruta',
    
    // Otras del Mundo
    'otras_title': 'OTRAS COSAS DEL MUNDO',
    'otras_description': 'Platos especiales de otras cocinas del mundo',
    
    // Salad protein options
    'salad_protein_none': 'Sin Proteína',
    'salad_protein_none_desc': 'Solo ingredientes de la ensalada',
    'salad_protein_chicken': 'Añadir Pollo',
    'salad_protein_chicken_desc': 'Ensalada con pollo tierno',
    'salad_protein_shrimp': 'Añadir Langostinos',
    'salad_protein_shrimp_desc': 'Ensalada con langostinos frescos',
    'salad_protein_both': 'Pollo y Langostinos',
    'salad_protein_both_desc': 'Ensalada con pollo y langostinos',
    
    // Drinks Products - Bebidas
    'drink_1': 'Coca Cola',
    'drink_1_desc': 'Coca Cola 0.33L',
    'drink_2': 'Coca Cola Zero',
    'drink_2_desc': 'Coca Cola Zero 0.33L',
    'drink_3': 'Fanta Naranja',
    'drink_3_desc': 'Fanta Naranja 0.33L',
    'drink_4': 'Fanta Limón',
    'drink_4_desc': 'Fanta Limón 0.33L',
    'drink_5': 'Nestea Limón',
    'drink_5_desc': 'Nestea Limón 0.33L',
    'drink_6': 'Nestea Maracuyá',
    'drink_6_desc': 'Nestea Maracuyá 0.33L',
    'drink_7': 'Aquarius Limón',
    'drink_7_desc': 'Aquarius Limón 0.33L',
    'drink_8': 'Aquarius Naranja',
    'drink_8_desc': 'Aquarius Naranja 0.33L',
    'drink_9': 'Sprite',
    'drink_9_desc': 'Sprite 0.33L',
    'drink_10': 'Agua',
    'drink_10_desc': 'Agua 0.33L',
    'drink_11': 'Agua con Gas',
    'drink_11_desc': 'Agua con Gas 0.33L',
    'drink_12': 'Zumo Manzana',
    'drink_12_desc': 'Zumo de Manzana 0.200L',
    'drink_13': 'Zumo Piña',
    'drink_13_desc': 'Zumo de Piña 0.200L',
    'drink_14': 'Zumo Naranja',
    'drink_14_desc': 'Zumo de Naranja 0.200L',
    'drink_15': 'Zumo Melocotón',
    'drink_15_desc': 'Zumo de Melocotón 0.200L',
    'drink_16': 'Zumo Tomate',
    'drink_16_desc': 'Zumo de Tomate 0.200L',
    'drink_17': 'Cerveza Shinga',
    'drink_17_desc': 'Cerveza Shinga 1/3',
    'drink_18': 'Cerveza Kirin',
    'drink_18_desc': 'Cerveza Kirin 1/3',
    'drink_19': 'Cerveza San Miguel Especial',
    'drink_19_desc': 'Cerveza San Miguel Especial 1/3',
    'drink_20': 'Cerveza San Miguel Sin Gluten',
    'drink_20_desc': 'Cerveza San Miguel Sin Gluten 1/3',
    'drink_21': 'Cerveza San Miguel 0.0',
    'drink_21_desc': 'Cerveza San Miguel 0.0 Sin Alcohol 1/3',
    'drink_22': 'Cerveza Alhambra Especial',
    'drink_22_desc': 'Cerveza Alhambra Especial 1/3',
    'drink_23': 'Cerveza Alhambra Sin Alcohol',
    'drink_23_desc': 'Cerveza Alhambra Sin Alcohol 1/3',
    'drink_26': 'Copa de Vino',
    'drink_26_desc': 'Copa de Vino',
    'drink_27': 'Botella de Vino',
    'drink_27_desc': 'Botella de Vino',
     'drink_28': 'Tinto de Verano',
    'drink_28_desc': 'Tinto de Verano',

    // Otros Extras (salsas y complementos)
    'step_extras': 'Otros Extras',
    'extras_title': 'Salsas y Complementos Extra',
    'extras_desc': 'Añade salsas o complementos adicionales a tu plato',
    'extras_label': 'Extras',
    'extra_soja': 'Salsa Soja',
    'extra_ostra': 'Salsa Ostra',
    'extra_tamarindo': 'Salsa Tamarindo',
    'extra_cacahuete': 'Salsa Cacahuete',
    'extra_teriyaki': 'Salsa Teriyaki',
    'extra_agridulce': 'Salsa Agridulce',
    'extra_siracha': 'Siracha (Picante)',
    'extra_vinagreta': 'Vinagreta',
    'extra_cesar': 'Salsa César',
    'extra_rosa': 'Salsa Rosa',
    'extra_fruta': 'Salsa de Fruta',
    'extra_mayonesa': 'Mayonesa',
    'extra_ketchup': 'Ketchup',
    'extra_arroz_vapor': 'Extra Arroz al Vapor',
    'extra_arroz_frito_huevo': 'Extra Arroz Frito con Huevo',
    'extra_arroz_curry_pina': 'Extra Arroz con Curry y Piña',
    'extra_arroz_japones': 'Extra Arroz Japonés',
    'extra_fruta_variada': 'Extra Fruta Mediana Variada',
    'extra_mochi': 'Extra Mochi',
    'extra_noodles_frito_huevo': 'Extra Noodles Frito con Huevo',
    'extra_patatas_fritas': 'Extra Patatas Fritas'
  },
  
  en: {
    // Header
    'cart': 'Cart',
    'phone': '951 40 19 37',
    'address': 'Plaza de la Solidaridad, 9 - Málaga',
    
    // Hero
    'prepare_to_taste': 'PREPARE IT',
    'to_your_liking': 'TO YOUR TASTE',
    'choose_what_you_like': 'Choose what you like most and...',
    'take_it_home': 'take it home!',
    'order_online': 'ORDER ONLINE',
     'call_us': 'CALL: 951 40 19 37',
     
     // Auth
     'auth_title': 'Sign In to Thaii Express',
     'login': 'Login',
     'signup': 'Sign Up',
     'email': 'Email',
     'password': 'Password',
     'loading': 'Loading...',
     'login_success': 'Login Successful!',
     'signup_success': 'Account Created!',
     'check_email_confirmation': 'Please check your email to confirm your account.',
     'logout': 'Logout',
     'myOrders': 'My Orders',
     
     // Main Categories
    'entrantes': 'Starters',
    'arroz': 'Rice',
    'tallarines': 'Noodles', 
    'sopas': 'Soups',
    'pokes': 'Pokes',
    'postres': 'Desserts',
    'ensaladas': 'Salads',
    'otras': 'World Dishes',
    'bebidas': 'Drinks',
    
    // Proteins
    'chicken': 'Chicken',
    'beef': 'Beef',
    'pork': 'Pork', 
    'shrimp': 'Shrimp',
    'vegetables': 'Vegetables',
    'select_protein': 'Select your protein',
    'protein_tab': 'Protein',
    
    // Sauces
    'teriyaki': 'Teriyaki',
    'sweet_sour': 'Sweet & Sour',
    'curry_sauce': 'Curry',
    'soy_sauce': 'Soy Sauce',
    'spicy_sauce': 'Spicy',
    'select_sauce': 'Select your sauce',
    'sauce_tab': 'Sauce',
    'spicy_level': 'Spicy level',
    
    // Rice Customizer
    'rice_customizer_title': 'Customize your Rice',
    'rice_customizer_description': 'Select your favorite protein and sauce to create your perfect dish',
    'customize_rice': 'Customize your rice',
    'selected_items': 'Selected items',
    
    // Subcategories
    'classic': 'Classic',
    'yellow_curry': 'Yellow Curry',
    'green_curry': 'Green Curry',
    'red_curry': 'Red Curry',
    
    // Common
    'price': 'Price',
    'add_to_cart': 'Add to cart',
    'vegetarian': 'Vegetarian',
    'spicy': 'Spicy',
    
    // Cart
    'your_cart': 'Your cart',
    'empty_cart': 'Your cart is empty',
    'quantity': 'Quantity',
    'remove': 'Remove',
    'subtotal': 'Subtotal',
    'delivery_fee': 'Delivery fee',
    'total': 'Total',
    'customer_info': 'Customer information',
    'name': 'Name',
    'phone_number': 'Phone',
    'address_full': 'Full address',
    'notes': 'Notes (optional)',
    'send_order_whatsapp': 'SEND ORDER VIA WHATSAPP',
    
    // Dialog
    'doubts_about_dishes': 'Have questions about our dishes?',
    'khopi_greeting': 'Hello! I\'m Khopi, the Thaii Express mascot. If you have questions about ingredients or need help choosing, call us!',
    'see_full_menu': 'SEE FULL MENU',
    
    // Footer
    'restaurant_description': 'Authentic Asian takeaway food. Prepare it to your taste and take it home.',
    'contact_title': 'CONTACT',
    'hours_title': 'OPENING HOURS',
    'monday_sunday': 'Monday - Sunday',
    'hours_time': '12:00 - 23:00',
    'online_orders_available': 'Online orders available during all opening hours',
    'all_rights_reserved': '© 2024 Thaii Express Málaga. All rights reserved.',
    'top_sales': 'Top Sales',
    
    // Loading and Error states
    'loading_products': 'Loading products...',
    'error_loading': 'Error',
    'retry': 'Retry',
    'coming_soon': 'Coming soon...',
    
    // Category descriptions
    'starters_description': 'Delicious starters to begin your culinary experience',
    'noodles_description': 'Traditional Asian noodles stir-fried with fresh vegetables',
    'soups_description': 'Comforting soups with authentic Asian cuisine flavors',
    'pokes_description': 'Fresh and healthy pokes with quality ingredients',
    'desserts_description': 'Delicious desserts to sweeten your experience',
    'salads_description': 'Fresh and nutritious salads with seasonal ingredients',
    'drinks_description': 'Refreshing drinks to accompany your meal',
    
    // Rice Customizer Proteins
    'chicken_protein': 'Chicken',
    'beef_protein': 'Beef',
    'shrimp_protein': 'Shrimp',
    'chicken_beef': 'Chicken & Beef',
    'chicken_shrimp': 'Chicken & Shrimp',
    'beef_shrimp': 'Beef & Shrimp',
    'mix_three': 'Chicken, Beef & Shrimp',
    
    // Rice Customizer Protein Descriptions
    'chicken_desc': 'Tender marinated chicken',
    'beef_desc': 'Juicy stir-fried beef',
    'shrimp_desc': 'Fresh sea shrimp',
    'chicken_beef_desc': 'Combination of chicken and beef',
    'chicken_shrimp_desc': 'Chicken with fresh shrimp',
    'beef_shrimp_desc': 'Beef with sea shrimp',
    'mix_three_desc': 'Complete protein combination',
    
    // Rice Customizer Sauces
    'classic_sauce': 'Classic Sauce',
    'original_sauce': 'Original Sauce',
    'teriyaki_sauce': 'Teriyaki Sauce',
    'yellow_curry_sauce': 'Yellow Curry',
    'green_curry_sauce': 'Green Curry',
    'red_curry_sauce': 'Red Curry',
    
    // Rice Customizer Sauce Descriptions
    'classic_sauce_desc': 'Traditional Asian sauce',
    'original_sauce_desc': 'Our special recipe',
    'teriyaki_sauce_desc': 'Sweet and savory Japanese sauce',
    'yellow_curry_sauce_desc': 'Mild yellow curry',
    'green_curry_sauce_desc': 'Medium spicy green curry',
    'red_curry_sauce_desc': 'Intense spicy red curry',
    
    // Spicy levels
    'medium_spicy': 'Medium spicy',
    'spicy_level_high': 'Spicy',
    
    // Custom rice creation
    'custom_rice_with': 'Fried rice with',
    'custom_rice_and': 'and',
    'custom_rice_desc': 'Custom fried rice with',

    // Noodle types
    'noodle_finos': 'Thin (Noodles)',
    'noodle_anchos': 'Wide (Pad Thai)',
    'noodle_glass': 'Glass',
    'noodle_udon': 'Udon',
    'noodle_finos_desc': 'Traditional thin noodles',
    'noodle_anchos_desc': 'Wide Pad Thai style noodles',
    'noodle_glass_desc': 'Transparent bean noodles',
    'noodle_udon_desc': 'Thick Japanese noodles',

    // Noodle customizer
    'noodle_customizer_title': 'CUSTOMIZE YOUR NOODLES',
    'noodle_customizer_description': 'Choose your noodle type, favorite protein and perfect sauce',
    'step_noodle_type': 'Noodle Type',
    'step_protein': 'Protein',
    'step_sauce': 'Sauce',
    'noodle_type': 'Noodle type',
    'custom_noodles_with': 'Custom noodles with',
    'custom_noodles_and': 'and',
    'custom_noodles_desc': 'Wok-fried noodles with',
    'custom_noodles_with_sauce': 'with sauce',
    'order_summary': 'Order summary',
    'protein': 'Protein',
    'sauce': 'Sauce',
    
    // Extra vegetables
    'extra_vegetables': 'Additional Vegetables',
    'extra_vegetables_optional': 'Additional Vegetables (Optional)',
    'extra_vegetables_desc': 'Select the extra vegetables you want to add to your dish',
    'extra_vegetables_label': 'Extra vegetables',
    'step_vegetables': 'Extra Vegetables',
    
    // Vegetable names
    'veg_egg': 'Egg',
    'veg_cilantro': 'Cilantro',
    'veg_basil': 'Basil',
    'veg_bean_sprouts': 'Bean Sprouts',
    'veg_red_onion': 'Red Onion',
    'veg_corn': 'Corn',
    'veg_green_beans': 'Green Beans',
    'veg_carrot': 'Carrot',
    'veg_peanut': 'Peanut',
    'veg_broccoli': 'Broccoli',
    'veg_scallion': 'Scallion',
    'veg_mushroom': 'Mushrooms',
    'veg_pepper': 'Pepper',

    // Enhanced protein translations
    'protein_chicken': 'Chicken',
    'protein_beef': 'Beef',
    'protein_shrimp': 'Shrimp',
    'protein_chicken_desc': 'Fresh and tender chicken breast',
    'protein_beef_desc': 'Premium tender beef',
    'protein_shrimp_desc': 'Fresh seafood shrimp',
    'protein_chicken_beef': 'Chicken & Beef',
    'protein_chicken_shrimp': 'Chicken & Shrimp',
    'protein_beef_shrimp': 'Beef & Shrimp',
    'protein_chicken_beef_shrimp': 'Chicken, Beef & Shrimp',
    'protein_chicken_beef_desc': 'Perfect combination of chicken and beef',
    'protein_chicken_shrimp_desc': 'Delicious mix of chicken and shrimp',
    'protein_beef_shrimp_desc': 'Exquisite combination of beef and shrimp',
    'protein_chicken_beef_shrimp_desc': 'Triple protein: chicken, beef and shrimp',

    // Enhanced sauce translations
    'sauce_classic': 'Classic',
    'sauce_original': 'Original',
    'sauce_teriyaki': 'Teriyaki',
    'sauce_classic_desc': 'Soy and oyster sauce',
    'sauce_original_desc': 'Cilantro, bean sprouts, carrot, peanut, tamarind sauce and lime',
    'sauce_teriyaki_desc': 'Traditional teriyaki sauce',
    
    // Entrantes translations - English (names and descriptions)
    'panko_chicken': 'Panko chicken (5 pieces)',
    'panko_chicken_desc': 'Crispy chicken pieces breaded with Japanese panko',
    'panko_shrimp': 'Panko shrimp (5 pieces)',
    'panko_shrimp_desc': 'Shrimp breaded with crispy panko',
    'chicken_skewer_1': 'Chicken skewer (1 piece)',
    'chicken_skewer_1_desc': 'Marinated grilled chicken skewer',
    'chicken_skewer_2': 'Chicken skewer (2 pieces)',
    'chicken_skewer_2_desc': 'Two marinated grilled chicken skewers',
    'shrimp_skewer_1': 'Shrimp skewer (1 piece)',
    'shrimp_skewer_1_desc': 'Fresh grilled shrimp skewer',
    'shrimp_skewer_2': 'Shrimp skewer (2 pieces)',
    'shrimp_skewer_2_desc': 'Two fresh grilled shrimp skewers',
    'mushroom_skewer_1': 'Mushroom skewer (1 piece)',
    'mushroom_skewer_1_desc': 'Fresh grilled mushroom skewer',
    'mushroom_skewer_2': 'Mushroom skewer (2 pieces)',
    'mushroom_skewer_2_desc': 'Two fresh grilled mushroom skewers',
    'grilled_salmon': 'Grilled salmon',
    'grilled_salmon_desc': 'Fresh grilled salmon fillet',
    'spring_rolls': 'Spring rolls (2 pieces)',
    'spring_rolls_desc': 'Crispy rolls filled with fresh vegetables',
    'shrimp_rolls': 'Shrimp rolls (8 pieces)',
    'shrimp_rolls_desc': 'Crispy rolls filled with fresh shrimp',
    'chicken_wings': 'Wings (6 pieces)',
    'chicken_wings_desc': 'Marinated and spiced chicken wings',
    'gyoza_fried': 'Fried shrimp gyoza (6 pieces)',
    'gyoza_fried_desc': 'Japanese dumplings filled with shrimp, fried preparation',
    'gyoza_grilled': 'Grilled shrimp gyoza (6 pieces)',
    'gyoza_grilled_desc': 'Japanese dumplings filled with shrimp, grilled preparation',
    'bao_chicken': 'Chicken bao (2 pieces)',
    'bao_chicken_desc': 'Asian steamed bun filled with tender chicken',
    'bao_shrimp': 'Shrimp bao (2 pieces)',
    'bao_shrimp_desc': 'Asian steamed bun filled with fresh shrimp',
    'edamame': 'Edamame',
    'edamame_desc': 'Boiled soybean pods with sea salt',
    'edamame_spicy': 'Spicy edamame',
    'edamame_spicy_desc': 'Boiled soybean pods with spicy seasoning',

    // Soup Customizer
    'soup_customizer_title': 'Customize your Soup',
    'soup_customizer_description': 'Choose your favorite soup type and protein',
    'step_soup_type': 'Choose your soup type',
    'soup_type': 'Soup type',
    'soup_miso': 'Miso Soup',
    'soup_miso_desc': 'Tofu, Wakame, Scallion and seafood sauce',
    'soup_tom_yam': 'Tom Yam Soup',
    'soup_tom_yam_desc': 'Mushrooms, carrot, broccoli, cherry tomatoes, seafood sauce, medium spicy',
    'custom_soup_with': 'Custom soup with',
    'custom_soup_desc': 'and your favorite ingredients',
    'prawn': 'Prawn',
    'veggie': 'Veggie',

    // Poke customizer
    'poke_customizer_title': 'Customize your Poke',
    'poke_customizer_description': 'Choose your favorite poke bowl with fresh ingredients',
    'step_poke_type': 'Poke Type',
    'choose_your_poke': 'Select your preferred poke',
    'poke_type': 'Poke Type',
    'selected': 'Selected',

    // Poke products
    'poke_korean_name': 'Korean Poke',
    'poke_korean_desc': 'Japanese vinegared rice base with soy sauce, Crispy Chicken, Kimchi, Kiwi, Tofu, prawns, seaweed, fried onion, sesame, soy sauce and kimchi sauce',
    'poke_japanese_name': 'Japanese Poke',
    'poke_japanese_desc': 'Japanese vinegared rice base with soy sauce, Wakame, avocado, sesame, Cherry tomatoes, kiwi, Salmon, prawns, Japanese sauce and soy sauce',
    'poke_indonesia_name': 'Indonesian Poke',
    'poke_indonesia_desc': 'Japanese vinegared rice base with soy sauce, Avocado, sesame, mango, pineapple, kiwi, Cherry tomatoes, cucumber, soy sauce and fruit sauce',
    'poke_thailand_name': 'Thailand Poke',
    'poke_thailand_desc': 'Japanese vinegared rice base with soy sauce, Avocado, pineapple, kiwi, prawns, sesame, fried onion, chicken, pepper sauce and fruit sauce',
    'poke_basic_name': 'Basic Poke',
    'poke_basic_desc': 'Choose to taste, select 150gr of chicken or 2 Crispy chicken, Sesame and 3 vegetables/fruits to choose from (wakame, kimchi, tofu, seaweed, cucumber, avocado, kiwi, cherry tomatoes, pineapple, strawberry, mango), plus choose one of our sauces (Kimchi, soy, Pink, fruit, Japanese, Caesar, sweet and sour)',
    'poke_premium_name': 'Premium Poke',
    'poke_premium_desc': 'Choose to taste, select 100gr of Salmon or 150gr of chicken or 2 Crispy chicken, Sesame and prawns, plus choose 4 vegetables/fruits from (wakame, kimchi, tofu, seaweed, cucumber, avocado, kiwi, cherry tomatoes, pineapple, strawberry, mango), plus choose one of our sauces (Kimchi, soy, Pink, fruit, Japanese, Caesar, sweet and sour)',
    
    // Salad Customizer
    'salad_customizer_title': 'CUSTOMIZE YOUR SALAD',
    'salad_customizer_description': 'Choose your favorite salad and preferred protein',
    'step_salad_type': 'Salad Type',
    'salad_type': 'Salad type',
    
    // Salad types
    'salad_cesar': 'Caesar Salad',
    'salad_cesar_ingredients': 'Lettuce, parmesan, avocado, tomato, croutons, vinaigrette and caesar sauce',
    'salad_classic_name': 'Classic Salad',
    'salad_classic_ingredients': 'Lettuce, parmesan, avocado, cherry tomatoes, cucumber, red onion, croutons, vinaigrette and caesar sauce',
     'salad_malaysia': 'Malaysia Salad',
    'salad_malaysia_ingredients': 'Lettuce, cucumber, croutons, cherry tomatoes, walnuts, caesar and vinaigrette sauce and wok vegetables',
    'salad_thai': 'Thai Salad',
    'salad_thai_ingredients': 'Lettuce, cherry tomatoes, peanut, chili, cucumber, mint, basil, vinaigrette and caesar sauce, wok beef',
    'salad_crispy': 'Crispy Salad',
    'salad_crispy_ingredients': 'Lettuce, carrots, bean sprouts, cherry tomatoes, vinaigrette and spicy pink sauce, choice of chicken or shrimp panko',
    'salad_fruit': 'Fruit Salad',
    'salad_fruit_ingredients': 'Lettuce, avocado, cherry tomatoes, mango, kiwi, strawberry and fruit sauce',
    
    // Otras del Mundo
    'otras_title': 'WORLD DISHES',
    'otras_description': 'Special dishes from world cuisines',
    
    // Salad protein options
    'salad_protein_none': 'No Protein',
    'salad_protein_none_desc': 'Salad ingredients only',
    'salad_protein_chicken': 'Add Chicken',
    'salad_protein_chicken_desc': 'Salad with tender chicken',
    'salad_protein_shrimp': 'Add Shrimp',
    'salad_protein_shrimp_desc': 'Salad with fresh shrimp',
    'salad_protein_both': 'Chicken and Shrimp',
    'salad_protein_both_desc': 'Salad with chicken and shrimp',
    
    // Drinks Products
    'drink_1': 'Coca Cola',
    'drink_1_desc': 'Coca Cola 0.33L',
    'drink_2': 'Coca Cola Zero',
    'drink_2_desc': 'Coca Cola Zero 0.33L',
    'drink_3': 'Fanta Orange',
    'drink_3_desc': 'Fanta Orange 0.33L',
    'drink_4': 'Fanta Lemon',
    'drink_4_desc': 'Fanta Lemon 0.33L',
    'drink_5': 'Nestea Lemon',
    'drink_5_desc': 'Nestea Lemon 0.33L',
    'drink_6': 'Nestea Passion Fruit',
    'drink_6_desc': 'Nestea Passion Fruit 0.33L',
    'drink_7': 'Aquarius Lemon',
    'drink_7_desc': 'Aquarius Lemon 0.33L',
    'drink_8': 'Aquarius Orange',
    'drink_8_desc': 'Aquarius Orange 0.33L',
    'drink_9': 'Sprite',
    'drink_9_desc': 'Sprite 0.33L',
    'drink_10': 'Water',
    'drink_10_desc': 'Water 0.33L',
    'drink_11': 'Sparkling Water',
    'drink_11_desc': 'Sparkling Water 0.33L',
    'drink_12': 'Apple Juice',
    'drink_12_desc': 'Apple Juice 0.200L',
    'drink_13': 'Pineapple Juice',
    'drink_13_desc': 'Pineapple Juice 0.200L',
    'drink_14': 'Orange Juice',
    'drink_14_desc': 'Orange Juice 0.200L',
    'drink_15': 'Peach Juice',
    'drink_15_desc': 'Peach Juice 0.200L',
    'drink_16': 'Tomato Juice',
    'drink_16_desc': 'Tomato Juice 0.200L',
    'drink_17': 'Shinga Beer',
    'drink_17_desc': 'Shinga Beer 1/3',
    'drink_18': 'Kirin Beer',
    'drink_18_desc': 'Kirin Beer 1/3',
    'drink_19': 'San Miguel Special Beer',
    'drink_19_desc': 'San Miguel Special Beer 1/3',
    'drink_20': 'San Miguel Gluten Free Beer',
    'drink_20_desc': 'San Miguel Gluten Free Beer 1/3',
    'drink_21': 'San Miguel 0.0 Beer',
    'drink_21_desc': 'San Miguel 0.0 Non-Alcoholic Beer 1/3',
    'drink_22': 'Alhambra Special Beer',
    'drink_22_desc': 'Alhambra Special Beer 1/3',
    'drink_23': 'Alhambra Non-Alcoholic Beer',
    'drink_23_desc': 'Alhambra Non-Alcoholic Beer 1/3',
    'drink_26': 'Glass of Wine',
    'drink_26_desc': 'Glass of Wine',
    'drink_27': 'Bottle of Wine',
    'drink_27_desc': 'Bottle of Wine',
     'drink_28': 'Tinto de Verano',
    'drink_28_desc': 'Tinto de Verano',

    // Other Extras (sauces and complements)
    'step_extras': 'Other Extras',
    'extras_title': 'Extra Sauces & Complements',
    'extras_desc': 'Add extra sauces or complements to your dish',
    'extras_label': 'Extras',
    'extra_soja': 'Soy Sauce',
    'extra_ostra': 'Oyster Sauce',
    'extra_tamarindo': 'Tamarind Sauce',
    'extra_cacahuete': 'Peanut Sauce',
    'extra_teriyaki': 'Teriyaki Sauce',
    'extra_agridulce': 'Sweet & Sour Sauce',
    'extra_siracha': 'Sriracha (Spicy)',
    'extra_vinagreta': 'Vinaigrette',
    'extra_cesar': 'Caesar Sauce',
    'extra_rosa': 'Pink Sauce',
    'extra_fruta': 'Fruit Sauce',
    'extra_mayonesa': 'Mayonnaise',
    'extra_ketchup': 'Ketchup',
    'extra_arroz_vapor': 'Extra Steamed Rice',
    'extra_arroz_frito_huevo': 'Extra Fried Rice with Egg',
    'extra_arroz_curry_pina': 'Extra Rice with Curry & Pineapple',
    'extra_arroz_japones': 'Extra Japanese Rice',
    'extra_fruta_variada': 'Extra Medium Fruit Mix',
    'extra_mochi': 'Extra Mochi',
    'extra_noodles_frito_huevo': 'Extra Fried Noodles with Egg',
    'extra_patatas_fritas': 'Extra French Fries'
  },
  
  fr: {
    // Header
    'cart': 'Panier',
    'phone': '951 40 19 37',
    'address': 'Plaza de la Solidaridad, 9 - Málaga',
    
    // Hero
    'prepare_to_taste': 'PRÉPAREZ-LE',
    'to_your_liking': 'À VOTRE GOÛT',
    'choose_what_you_like': 'Choisissez ce que vous aimez le plus et...',
    'take_it_home': 'emportez-le chez vous!',
    'order_online': 'COMMANDER EN LIGNE',
    'call_us': 'APPELER: 951 40 19 37',
    
    // Auth
    'auth_title': 'Connexion à Thaii Express',
    'login': 'Connexion',
    'signup': 'S\'inscrire',
    'email': 'Email',
    'password': 'Mot de passe',
    'loading': 'Chargement...',
    'login_success': 'Connexion réussie!',
    'signup_success': 'Compte créé!',
    'check_email_confirmation': 'Veuillez vérifier votre email pour confirmer votre compte.',
    'logout': 'Déconnexion',
    'myOrders': 'Mes Commandes',
    
    // Main Categories
    'entrantes': 'Entrées',
    'arroz': 'Riz',
    'tallarines': 'Nouilles',
    'sopas': 'Soupes', 
    'pokes': 'Pokes',
    'postres': 'Desserts',
    'ensaladas': 'Salades',
    'otras': 'Plats du Monde',
    'bebidas': 'Boissons',
    
    // Proteins
    'chicken': 'Poulet',
    'beef': 'Bœuf',
    'pork': 'Porc',
    'shrimp': 'Crevettes', 
    'vegetables': 'Légumes',
    'select_protein': 'Sélectionnez votre protéine',
    'protein_tab': 'Protéine',
    
    // Sauces
    'teriyaki': 'Teriyaki',
    'sweet_sour': 'Aigre-douce',
    'curry_sauce': 'Curry',
    'soy_sauce': 'Sauce soja',
    'spicy_sauce': 'Épicée',
    'select_sauce': 'Sélectionnez votre sauce',
    'sauce_tab': 'Sauce',
    'spicy_level': 'Niveau épicé',
    
    // Rice Customizer
    'rice_customizer_title': 'Personnalisez votre Riz',
    'rice_customizer_description': 'Sélectionnez votre protéine et sauce préférées pour créer votre plat parfait',
    'customize_rice': 'Personnalisez votre riz',
    'selected_items': 'Éléments sélectionnés',
    
    // Subcategories
    'classic': 'Classique',
    'yellow_curry': 'Curry Jaune',
    'green_curry': 'Curry Vert',
    'red_curry': 'Curry Rouge',
    
    // Common
    'price': 'Prix',
    'add_to_cart': 'Ajouter au panier',
    'vegetarian': 'Végétarien',
    'spicy': 'Épicé',
    
    // Cart
    'your_cart': 'Votre panier',
    'empty_cart': 'Votre panier est vide',
    'quantity': 'Quantité',
    'remove': 'Supprimer',
    'subtotal': 'Sous-total',
    'delivery_fee': 'Frais de livraison',
    'total': 'Total',
    'customer_info': 'Informations client',
    'name': 'Nom',
    'phone_number': 'Téléphone',
    'address_full': 'Adresse complète',
    'notes': 'Notes (optionnel)',
    'send_order_whatsapp': 'ENVOYER LA COMMANDE PAR WHATSAPP',
    
    // Dialog
    'doubts_about_dishes': 'Vous avez des questions sur nos plats?',
    'khopi_greeting': 'Bonjour! Je suis Khopi, la mascotte de Thaii Express. Si vous avez des questions sur les ingrédients ou besoin d\'aide pour choisir, appelez-nous!',
    'see_full_menu': 'VOIR LE MENU COMPLET',
    
    // Footer
    'restaurant_description': 'Cuisine asiatique authentique à emporter. Préparez-la à votre goût et emportez-la chez vous.',
    'contact_title': 'CONTACT',
    'hours_title': 'HORAIRES',
    'monday_sunday': 'Lundi - Dimanche',
    'hours_time': '12:00 - 23:00',
    'online_orders_available': 'Commandes en ligne disponibles pendant toutes les heures d\'ouverture',
    'all_rights_reserved': '© 2024 Thaii Express Málaga. Tous droits réservés.',
    'top_sales': 'Meilleures ventes',
    
    // Loading and Error states
    'loading_products': 'Chargement des produits...',
    'error_loading': 'Erreur',
    'retry': 'Réessayer',
    'coming_soon': 'Bientôt disponible...',
    
    // Category descriptions
    'starters_description': 'Délicieuses entrées pour commencer votre expérience culinaire',
    'noodles_description': 'Nouilles asiatiques traditionnelles sautées avec des légumes frais',
    'soups_description': 'Soupes réconfortantes aux saveurs authentiques de la cuisine asiatique',
    'pokes_description': 'Pokes frais et sains avec des ingrédients de qualité',
    'desserts_description': 'Délicieux desserts pour adoucir votre expérience',
    'salads_description': 'Salades fraîches et nutritives avec des ingrédients de saison',
    'drinks_description': 'Boissons rafraîchissantes pour accompagner votre repas',
    
    // Rice Customizer Proteins
    'chicken_protein': 'Poulet',
    'beef_protein': 'Bœuf',
    'shrimp_protein': 'Crevettes',
    'chicken_beef': 'Poulet et Bœuf',
    'chicken_shrimp': 'Poulet et Crevettes',
    'beef_shrimp': 'Bœuf et Crevettes',
    'mix_three': 'Poulet, Bœuf et Crevettes',
    
    // Rice Customizer Protein Descriptions
    'chicken_desc': 'Poulet tendre mariné',
    'beef_desc': 'Bœuf juteux sauté',
    'shrimp_desc': 'Crevettes fraîches de mer',
    'chicken_beef_desc': 'Combinaison de poulet et bœuf',
    'chicken_shrimp_desc': 'Poulet avec crevettes fraîches',
    'beef_shrimp_desc': 'Bœuf avec crevettes de mer',
    'mix_three_desc': 'Combinaison complète de protéines',
    
    // Rice Customizer Sauces
    'classic_sauce': 'Sauce Classique',
    'original_sauce': 'Sauce Originale',
    'teriyaki_sauce': 'Sauce Teriyaki',
    'yellow_curry_sauce': 'Curry Jaune',
    'green_curry_sauce': 'Curry Vert',
    'red_curry_sauce': 'Curry Rouge',
    
    // Rice Customizer Sauce Descriptions
    'classic_sauce_desc': 'Sauce asiatique traditionnelle',
    'original_sauce_desc': 'Notre recette spéciale',
    'teriyaki_sauce_desc': 'Sauce japonaise douce et savoureuse',
    'yellow_curry_sauce_desc': 'Curry jaune doux',
    'green_curry_sauce_desc': 'Curry vert moyennement épicé',
    'red_curry_sauce_desc': 'Curry rouge intense et épicé',
    
    // Spicy levels
    'medium_spicy': 'Moyennement épicé',
    'spicy_level_high': 'Épicé',
    
    // Custom rice creation
    'custom_rice_with': 'Riz frit avec',
    'custom_rice_and': 'et',
    'custom_rice_desc': 'Riz frit personnalisé avec',

    // Noodle types
    'noodle_finos': 'Fins (Nouilles)',
    'noodle_anchos': 'Larges (Pad Thai)',
    'noodle_glass': 'Vermicelles',
    'noodle_udon': 'Udon',
    'noodle_finos_desc': 'Nouilles fines traditionnelles',
    'noodle_anchos_desc': 'Nouilles larges style Pad Thai',
    'noodle_glass_desc': 'Vermicelles transparents de haricots',
    'noodle_udon_desc': 'Nouilles japonaises épaisses',

    // Noodle customizer
    'noodle_customizer_title': 'PERSONNALISEZ VOS NOUILLES',
    'noodle_customizer_description': 'Choisissez votre type de nouilles, protéine préférée et sauce parfaite',
    'step_noodle_type': 'Type de Nouilles',
    'step_protein': 'Protéine',
    'step_sauce': 'Sauce',
    'noodle_type': 'Type de nouilles',
    'custom_noodles_with': 'Nouilles personnalisées avec',
    'custom_noodles_and': 'et',
    'custom_noodles_desc': 'Nouilles sautées au wok avec',
    'custom_noodles_with_sauce': 'avec sauce',
    'order_summary': 'Résumé de commande',
    'protein': 'Protéine',
    'sauce': 'Sauce',
    
    // Extra vegetables
    'extra_vegetables': 'Légumes Supplémentaires',
    'extra_vegetables_optional': 'Légumes Supplémentaires (Optionnel)',
    'extra_vegetables_desc': 'Sélectionnez les légumes supplémentaires que vous souhaitez ajouter à votre plat',
    'extra_vegetables_label': 'Légumes supplémentaires',
    'step_vegetables': 'Légumes Supplémentaires',
    
    // Vegetable names
    'veg_egg': 'Œuf',
    'veg_cilantro': 'Coriandre',
    'veg_basil': 'Basilic',
    'veg_bean_sprouts': 'Pousses de Soja',
    'veg_red_onion': 'Oignon rouge',
    'veg_corn': 'Maïs',
    'veg_green_beans': 'Haricots verts',
    'veg_carrot': 'Carotte',
    'veg_peanut': 'Cacahuète',
    'veg_broccoli': 'Brocoli',
    'veg_scallion': 'Ciboulette',
    'veg_mushroom': 'Champignons',
    'veg_pepper': 'Poivron',

    // Enhanced protein translations
    'protein_chicken': 'Poulet',
    'protein_beef': 'Bœuf',
    'protein_shrimp': 'Crevettes',
    'protein_chicken_desc': 'Blanc de poulet frais et tendre',
    'protein_beef_desc': 'Bœuf tendre de première qualité',
    'protein_shrimp_desc': 'Crevettes fraîches de mer',
    'protein_chicken_beef': 'Poulet et Bœuf',
    'protein_chicken_shrimp': 'Poulet et Crevettes',
    'protein_beef_shrimp': 'Bœuf et Crevettes',
    'protein_chicken_beef_shrimp': 'Poulet, Bœuf et Crevettes',
    'protein_chicken_beef_desc': 'Combinaison parfaite de poulet et bœuf',
    'protein_chicken_shrimp_desc': 'Délicieux mélange de poulet et crevettes',
    'protein_beef_shrimp_desc': 'Combinaison exquise de bœuf et crevettes',
    'protein_chicken_beef_shrimp_desc': 'Triple protéine : poulet, bœuf et crevettes',

    // Enhanced sauce translations
    'sauce_classic': 'Classique',
    'sauce_original': 'Original',
    'sauce_teriyaki': 'Teriyaki',
    'sauce_classic_desc': 'Sauce soja et huîtres',
    'sauce_original_desc': 'Coriandre, pousses de soja, carotte, cacahuète, sauce tamarin et citron vert',
    'sauce_teriyaki_desc': 'Sauce teriyaki traditionnelle',
    
    // Entrantes translations - French (names and descriptions)
    'panko_chicken': 'Panko poulet (5 pièces)',
    'panko_chicken_desc': 'Morceaux de poulet croustillants panés au panko japonais',
    'panko_shrimp': 'Panko crevettes (5 pièces)',
    'panko_shrimp_desc': 'Crevettes panées au panko croustillant',
    'chicken_skewer_1': 'Brochette de poulet (1 pièce)',
    'chicken_skewer_1_desc': 'Brochette de poulet mariné grillé',
    'chicken_skewer_2': 'Brochette de poulet (2 pièces)',
    'chicken_skewer_2_desc': 'Deux brochettes de poulet mariné grillé',
    'shrimp_skewer_1': 'Brochette de crevettes (1 pièce)',
    'shrimp_skewer_1_desc': 'Brochette de crevettes fraîches grillées',
    'shrimp_skewer_2': 'Brochette de crevettes (2 pièces)',
    'shrimp_skewer_2_desc': 'Deux brochettes de crevettes fraîches grillées',
    'mushroom_skewer_1': 'Brochette de champignons (1 pièce)',
    'mushroom_skewer_1_desc': 'Brochette de champignons frais grillés',
    'mushroom_skewer_2': 'Brochette de champignons (2 pièces)',
    'mushroom_skewer_2_desc': 'Deux brochettes de champignons frais grillés',
    'grilled_salmon': 'Saumon grillé',
    'grilled_salmon_desc': 'Filet de saumon frais grillé',
    'spring_rolls': 'Rouleaux de printemps (2 pièces)',
    'spring_rolls_desc': 'Rouleaux croustillants farcis aux légumes frais',
    'shrimp_rolls': 'Rouleaux de crevettes (8 pièces)',
    'shrimp_rolls_desc': 'Rouleaux croustillants farcis aux crevettes fraîches',
    'chicken_wings': 'Ailes (6 pièces)',
    'chicken_wings_desc': 'Ailes de poulet marinées et épicées',
    'gyoza_fried': 'Gyoza crevettes frits (6 pièces)',
    'gyoza_fried_desc': 'Raviolis japonais farcis aux crevettes, préparation frite',
    'gyoza_grilled': 'Gyoza crevettes plancha (6 pièces)',
    'gyoza_grilled_desc': 'Raviolis japonais farcis aux crevettes, préparation plancha',
    'bao_chicken': 'Bao poulet (2 pièces)',
    'bao_chicken_desc': 'Pain cuit à la vapeur asiatique farci au poulet tendre',
    'bao_shrimp': 'Bao crevettes (2 pièces)',
    'bao_shrimp_desc': 'Pain cuit à la vapeur asiatique farci aux crevettes fraîches',
    'edamame': 'Edamame',
    'edamame_desc': 'Gousses de soja bouillies au sel marin',
    'edamame_spicy': 'Edamame épicé',
    'edamame_spicy_desc': 'Gousses de soja bouillies aux épices piquantes',

    // Soup Customizer
    'soup_customizer_title': 'Personnalisez votre Soupe',
    'soup_customizer_description': 'Choisissez votre type de soupe préféré et votre protéine',
    'step_soup_type': 'Choisissez votre type de soupe',
    'soup_type': 'Type de soupe',
    'soup_miso': 'Soupe Miso',
    'soup_miso_desc': 'Tofu, Wakame, Ciboulette et sauce aux fruits de mer',
    'soup_tom_yam': 'Soupe Tom Yam',
    'soup_tom_yam_desc': 'Champignons, carotte, brocoli, tomates cerises, sauce aux fruits de mer, moyennement épicé',
    'custom_soup_with': 'Soupe personnalisée avec',
    'custom_soup_desc': 'et vos ingrédients préférés',
    'prawn': 'Crevette',
    'veggie': 'Végétarien',

    // Poke customizer
    'poke_customizer_title': 'Personnalisez votre Poké',
    'poke_customizer_description': 'Choisissez votre poke bowl préféré avec des ingrédients frais',
    'step_poke_type': 'Type de Poké',
    'choose_your_poke': 'Sélectionnez votre poké préféré',
    'poke_type': 'Type de Poké',
    'selected': 'Sélectionné',

    // Poke products
    'poke_korean_name': 'Poké Coréen',
    'poke_korean_desc': 'Base de riz japonais vinaigré avec sauce soja, Poulet Crispy, Kimchi, Kiwi, Tofu, crevettes, algue, oignon frit, sésame, sauce soja et sauce kimchi',
    'poke_japanese_name': 'Poké Japonais',
    'poke_japanese_desc': 'Base de riz japonais vinaigré avec sauce soja, Wakame, avocat, sésame, Tomates cerises, kiwi, Saumon, crevettes, sauce japonaise et sauce soja',
    'poke_indonesia_name': 'Poké Indonésien',
    'poke_indonesia_desc': 'Base de riz japonais vinaigré avec sauce soja, Avocat, sésame, mangue, ananas, kiwi, Tomates cerises, concombre, sauce soja et sauce aux fruits',
    'poke_thailand_name': 'Poké Thaïlandais',
    'poke_thailand_desc': 'Base de riz japonais vinaigré avec sauce soja, Avocat, ananas, kiwi, crevettes, sésame, oignon frit, poulet, sauce poivre et sauce aux fruits',
    'poke_basic_name': 'Poké Basique',
    'poke_basic_desc': 'Choix au goût, choisissez 150gr de poulet ou 2 poulets Crispy, Sésame et 3 légumes/fruits à choisir parmi (wakame, kimchi, tofu, algue, concombre, avocat, kiwi, tomates cerises, ananas, fraise, mangue), plus choisir une de nos sauces (Kimchi, soja, Rose, fruit, Japonaise, César, aigre-douce)',
    'poke_premium_name': 'Poké Premium',
    'poke_premium_desc': 'Choix au goût, choisissez 100gr de Saumon ou 150gr de poulet ou 2 poulets Crispy, Sésame et crevettes, plus choisir 4 légumes/fruits parmi (wakame, kimchi, tofu, algue, concombre, avocat, kiwi, tomates cerises, ananas, fraise, mangue), plus choisir une de nos sauces (Kimchi, soja, Rose, fruit, Japonaise, César, aigre-douce)',
    
    // Salad Customizer
    'salad_customizer_title': 'PERSONNALISEZ VOTRE SALADE',
    'salad_customizer_description': 'Choisissez votre salade préférée et la protéine de votre choix',
    'step_salad_type': 'Type de Salade',
    'salad_type': 'Type de salade',
    
    // Salad types
    'salad_cesar': 'Salade César',
    'salad_cesar_ingredients': 'Laitue, Parmesan, Avocat, Tomates cerises, croûtons, vinaigrette et sauce césar',
    'salad_classic_name': 'Salade Classic',
    'salad_classic_ingredients': 'Laitue, Parmesan, Avocat, Tomates cerises, concombre, oignon rouge, croûtons, vinaigrette et sauce césar',
     'salad_malaysia': 'Salade Malaysia',
    'salad_malaysia_ingredients': 'Laitue, concombre, croûtons, tomates cerises, noix, sauces césar et vinaigrette et légumes au wok',
    'salad_thai': 'Salade Thaïlandaise',
    'salad_thai_ingredients': 'Laitue, tomates cerises, cacahuète, piment, concombre, menthe, basilic, sauces vinaigrette et césar, bœuf au wok',
    'salad_crispy': 'Salade Crispy',
    'salad_crispy_ingredients': 'Laitue, carottes, germes de soja, tomates cerises, sauces vinaigrette et rose épicée, panko poulet ou crevettes au choix',
    'salad_fruit': 'Salade de Fruits',
    'salad_fruit_ingredients': 'Laitue, avocat, tomates cerises, mangue, kiwi, fraise et sauce aux fruits',
    
    // Otras del Mundo
    'otras_title': 'PLATS DU MONDE',
    'otras_description': 'Plats spéciaux des cuisines du monde',
    
    // Salad protein options
    'salad_protein_none': 'Sans Protéine',
    'salad_protein_none_desc': 'Ingrédients de la salade uniquement',
    'salad_protein_chicken': 'Ajouter Poulet',
    'salad_protein_chicken_desc': 'Salade avec poulet tendre',
    'salad_protein_shrimp': 'Ajouter Crevettes',
    'salad_protein_shrimp_desc': 'Salade avec crevettes fraîches',
    'salad_protein_both': 'Poulet et Crevettes',
    'salad_protein_both_desc': 'Salade avec poulet et crevettes',
    
    // Drinks Products
    'drink_1': 'Coca Cola',
    'drink_1_desc': 'Coca Cola 0.33L',
    'drink_2': 'Coca Cola Zero',
    'drink_2_desc': 'Coca Cola Zero 0.33L',
    'drink_3': 'Fanta Orange',
    'drink_3_desc': 'Fanta Orange 0.33L',
    'drink_4': 'Fanta Citron',
    'drink_4_desc': 'Fanta Citron 0.33L',
    'drink_5': 'Nestea Citron',
    'drink_5_desc': 'Nestea Citron 0.33L',
    'drink_6': 'Nestea Fruit de la Passion',
    'drink_6_desc': 'Nestea Fruit de la Passion 0.33L',
    'drink_7': 'Aquarius Citron',
    'drink_7_desc': 'Aquarius Citron 0.33L',
    'drink_8': 'Aquarius Orange',
    'drink_8_desc': 'Aquarius Orange 0.33L',
    'drink_9': 'Sprite',
    'drink_9_desc': 'Sprite 0.33L',
    'drink_10': 'Eau',
    'drink_10_desc': 'Eau 0.33L',
    'drink_11': 'Eau Gazeuse',
    'drink_11_desc': 'Eau Gazeuse 0.33L',
    'drink_12': 'Jus de Pomme',
    'drink_12_desc': 'Jus de Pomme 0.200L',
    'drink_13': 'Jus d\'Ananas',
    'drink_13_desc': 'Jus d\'Ananas 0.200L',
    'drink_14': 'Jus d\'Orange',
    'drink_14_desc': 'Jus d\'Orange 0.200L',
    'drink_15': 'Jus de Pêche',
    'drink_15_desc': 'Jus de Pêche 0.200L',
    'drink_16': 'Jus de Tomate',
    'drink_16_desc': 'Jus de Tomate 0.200L',
    'drink_17': 'Bière Shinga',
    'drink_17_desc': 'Bière Shinga 1/3',
    'drink_18': 'Bière Kirin',
    'drink_18_desc': 'Bière Kirin 1/3',
    'drink_19': 'Bière San Miguel Spéciale',
    'drink_19_desc': 'Bière San Miguel Spéciale 1/3',
    'drink_20': 'Bière San Miguel Sans Gluten',
    'drink_20_desc': 'Bière San Miguel Sans Gluten 1/3',
    'drink_21': 'Bière San Miguel 0.0',
    'drink_21_desc': 'Bière San Miguel 0.0 Sans Alcool 1/3',
    'drink_22': 'Bière Alhambra Spéciale',
    'drink_22_desc': 'Bière Alhambra Spéciale 1/3',
    'drink_23': 'Bière Alhambra Sans Alcool',
    'drink_23_desc': 'Bière Alhambra Sans Alcool 1/3',
    'drink_26': 'Verre de Vin',
    'drink_26_desc': 'Verre de Vin',
    'drink_27': 'Bouteille de Vin',
    'drink_27_desc': 'Bouteille de Vin',
     'drink_28': 'Tinto de Verano',
    'drink_28_desc': 'Tinto de Verano',

    // Extras supplémentaires (sauces et compléments)
    'step_extras': 'Autres Extras',
    'extras_title': 'Sauces et Compléments Extra',
    'extras_desc': 'Ajoutez des sauces ou compléments supplémentaires à votre plat',
    'extras_label': 'Extras',
    'extra_soja': 'Sauce Soja',
    'extra_ostra': 'Sauce Huîtres',
    'extra_tamarindo': 'Sauce Tamarin',
    'extra_cacahuete': 'Sauce Cacahuète',
    'extra_teriyaki': 'Sauce Teriyaki',
    'extra_agridulce': 'Sauce Aigre-douce',
    'extra_siracha': 'Sriracha (Épicée)',
    'extra_vinagreta': 'Vinaigrette',
    'extra_cesar': 'Sauce César',
    'extra_rosa': 'Sauce Rose',
    'extra_fruta': 'Sauce aux Fruits',
    'extra_mayonesa': 'Mayonnaise',
    'extra_ketchup': 'Ketchup',
    'extra_arroz_vapor': 'Extra Riz Vapeur',
    'extra_arroz_frito_huevo': 'Extra Riz Frit avec Œuf',
    'extra_arroz_curry_pina': 'Extra Riz Curry & Ananas',
    'extra_arroz_japones': 'Extra Riz Japonais',
    'extra_fruta_variada': 'Extra Fruits Variés Moyen',
    'extra_mochi': 'Extra Mochi',
    'extra_noodles_frito_huevo': 'Extra Nouilles Frites avec Œuf',
    'extra_patatas_fritas': 'Extra Frites'
  },
  
  de: {
    // Header
    'cart': 'Warenkorb',
    'phone': '951 40 19 37',
    'address': 'Plaza de la Solidaridad, 9 - Málaga',
    
    // Hero
    'prepare_to_taste': 'BEREITEN SIE ES',
    'to_your_liking': 'NACH IHREM GESCHMACK',
    'choose_what_you_like': 'Wählen Sie, was Ihnen am besten gefällt und...',
    'take_it_home': 'nehmen Sie es mit nach Hause!',
    'order_online': 'ONLINE BESTELLEN',
    'call_us': 'ANRUFEN: 951 40 19 37',
    
    // Auth
    'auth_title': 'Bei Thaii Express anmelden',
    'login': 'Anmelden',
    'signup': 'Registrieren',
    'email': 'E-Mail',
    'password': 'Passwort',
    'loading': 'Laden...',
    'login_success': 'Anmeldung erfolgreich!',
    'signup_success': 'Konto erstellt!',
    'check_email_confirmation': 'Bitte überprüfen Sie Ihre E-Mail, um Ihr Konto zu bestätigen.',
    'logout': 'Abmelden',
    'myOrders': 'Meine Bestellungen',
    
    // Main Categories
    'entrantes': 'Vorspeisen',
    'arroz': 'Reis',
    'tallarines': 'Nudeln',
    'sopas': 'Suppen',
    'pokes': 'Pokes',
    'postres': 'Desserts',
    'ensaladas': 'Salate',
    'otras': 'Weltgerichte',
    'bebidas': 'Getränke',
    
    // Proteins
    'chicken': 'Hähnchen',
    'beef': 'Rindfleisch',
    'pork': 'Schweinefleisch',
    'shrimp': 'Garnelen',
    'vegetables': 'Gemüse',
    'select_protein': 'Wählen Sie Ihr Protein',
    'protein_tab': 'Protein',
    
    // Sauces
    'teriyaki': 'Teriyaki',
    'sweet_sour': 'Süß-Sauer',
    'curry_sauce': 'Curry',
    'soy_sauce': 'Sojasauce',
    'spicy_sauce': 'Scharf',
    'select_sauce': 'Wählen Sie Ihre Sauce',
    'sauce_tab': 'Sauce',
    'spicy_level': 'Schärfegrad',
    
    // Rice Customizer
    'rice_customizer_title': 'Passen Sie Ihren Reis an',
    'rice_customizer_description': 'Wählen Sie Ihr Lieblingsprotein und Ihre Lieblingssauce, um Ihr perfektes Gericht zu kreieren',
    'customize_rice': 'Reis anpassen',
    'selected_items': 'Ausgewählte Artikel',
    
    // Subcategories
    'classic': 'Klassisch',
    'yellow_curry': 'Gelbes Curry',
    'green_curry': 'Grünes Curry',
    'red_curry': 'Rotes Curry',
    
    // Common
    'price': 'Preis',
    'add_to_cart': 'In den Warenkorb',
    'vegetarian': 'Vegetarisch',
    'spicy': 'Scharf',
    
    // Cart
    'your_cart': 'Ihr Warenkorb',
    'empty_cart': 'Ihr Warenkorb ist leer',
    'quantity': 'Menge',
    'remove': 'Entfernen',
    'subtotal': 'Zwischensumme',
    'delivery_fee': 'Liefergebühr',
    'total': 'Gesamt',
    'customer_info': 'Kundeninformationen',
    'name': 'Name',
    'phone_number': 'Telefon',
    'address_full': 'Vollständige Adresse',
    'notes': 'Notizen (optional)',
    'send_order_whatsapp': 'BESTELLUNG PER WHATSAPP SENDEN',
    
    // Dialog
    'doubts_about_dishes': 'Haben Sie Fragen zu unseren Gerichten?',
    'khopi_greeting': 'Hallo! Ich bin Khopi, das Maskottchen von Thaii Express. Wenn Sie Fragen zu Zutaten haben oder Hilfe bei der Auswahl brauchen, rufen Sie uns an!',
    'see_full_menu': 'VOLLSTÄNDIGES MENÜ ANSEHEN',
    
    // Footer
    'restaurant_description': 'Authentisches asiatisches Essen zum Mitnehmen. Bereiten Sie es nach Ihrem Geschmack zu und nehmen Sie es mit nach Hause.',
    'contact_title': 'KONTAKT',
    'hours_title': 'ÖFFNUNGSZEITEN',
    'monday_sunday': 'Montag - Sonntag',
    'hours_time': '12:00 - 23:00',
    'online_orders_available': 'Online-Bestellungen während der gesamten Öffnungszeiten verfügbar',
    'all_rights_reserved': '© 2024 Thaii Express Málaga. Alle Rechte vorbehalten.',
    'top_sales': 'Bestseller',
    
    // Loading and Error states
    'loading_products': 'Produkte laden...',
    'error_loading': 'Fehler',
    'retry': 'Wiederholen',
    'coming_soon': 'Demnächst verfügbar...',
    
    // Category descriptions
    'starters_description': 'Köstliche Vorspeisen, um Ihr kulinarisches Erlebnis zu beginnen',
    'noodles_description': 'Traditionelle asiatische Nudeln gebraten mit frischem Gemüse',
    'soups_description': 'Wohltuende Suppen mit authentischen asiatischen Geschmacksrichtungen',
    'pokes_description': 'Frische und gesunde Pokes mit hochwertigen Zutaten',
    'desserts_description': 'Köstliche Desserts, um Ihr Erlebnis zu versüßen',
    'salads_description': 'Frische und nahrhafte Salate mit saisonalen Zutaten',
    'drinks_description': 'Erfrischende Getränke zu Ihrer Mahlzeit',
    
    // Rice Customizer Proteins
    'chicken_protein': 'Hähnchen',
    'beef_protein': 'Rindfleisch',
    'shrimp_protein': 'Garnelen',
    'chicken_beef': 'Hähnchen & Rindfleisch',
    'chicken_shrimp': 'Hähnchen & Garnelen',
    'beef_shrimp': 'Rindfleisch & Garnelen',
    'mix_three': 'Hähnchen, Rindfleisch & Garnelen',
    
    // Rice Customizer Protein Descriptions
    'chicken_desc': 'Zartes mariniertes Hähnchen',
    'beef_desc': 'Saftiges gebratenes Rindfleisch',
    'shrimp_desc': 'Frische Meeresgarnelen',
    'chicken_beef_desc': 'Kombination aus Hähnchen und Rindfleisch',
    'chicken_shrimp_desc': 'Hähnchen mit frischen Garnelen',
    'beef_shrimp_desc': 'Rindfleisch mit Meeresgarnelen',
    'mix_three_desc': 'Komplette Proteinkombination',
    
    // Rice Customizer Sauces
    'classic_sauce': 'Klassische Sauce',
    'original_sauce': 'Originalsauce',
    'teriyaki_sauce': 'Teriyaki-Sauce',
    'yellow_curry_sauce': 'Gelbes Curry',
    'green_curry_sauce': 'Grünes Curry',
    'red_curry_sauce': 'Rotes Curry',
    
    // Rice Customizer Sauce Descriptions
    'classic_sauce_desc': 'Traditionelle asiatische Sauce',
    'original_sauce_desc': 'Unser Spezialrezept',
    'teriyaki_sauce_desc': 'Süße und herzhafte japanische Sauce',
    'yellow_curry_sauce_desc': 'Mildes gelbes Curry',
    'green_curry_sauce_desc': 'Mittelscharfes grünes Curry',
    'red_curry_sauce_desc': 'Intensives scharfes rotes Curry',
    
    // Spicy levels
    'medium_spicy': 'Mittelscharf',
    'spicy_level_high': 'Scharf',
    
    // Custom rice creation
    'custom_rice_with': 'Gebratener Reis mit',
    'custom_rice_and': 'und',
    'custom_rice_desc': 'Individueller gebratener Reis mit',

    // Noodle types
    'noodle_finos': 'Dünn (Nudeln)',
    'noodle_anchos': 'Breit (Pad Thai)',
    'noodle_glass': 'Glasnudeln',
    'noodle_udon': 'Udon',
    'noodle_finos_desc': 'Traditionelle dünne Nudeln',
    'noodle_anchos_desc': 'Breite Pad Thai-Nudeln',
    'noodle_glass_desc': 'Transparente Bohnennudeln',
    'noodle_udon_desc': 'Dicke japanische Nudeln',

    // Noodle customizer
    'noodle_customizer_title': 'PASSEN SIE IHRE NUDELN AN',
    'noodle_customizer_description': 'Wählen Sie Ihre Nudelsorte, Lieblingsprotein und perfekte Sauce',
    'step_noodle_type': 'Nudelsorte',
    'step_protein': 'Protein',
    'step_sauce': 'Sauce',
    'noodle_type': 'Nudelsorte',
    'custom_noodles_with': 'Individuelle Nudeln mit',
    'custom_noodles_and': 'und',
    'custom_noodles_desc': 'Im Wok gebratene Nudeln mit',
    'custom_noodles_with_sauce': 'mit Sauce',
    'order_summary': 'Bestellübersicht',
    'protein': 'Protein',
    'sauce': 'Sauce',
    
    // Extra vegetables
    'extra_vegetables': 'Zusätzliches Gemüse',
    'extra_vegetables_optional': 'Zusätzliches Gemüse (Optional)',
    'extra_vegetables_desc': 'Wählen Sie das zusätzliche Gemüse, das Sie Ihrem Gericht hinzufügen möchten',
    'extra_vegetables_label': 'Zusätzliches Gemüse',
    'step_vegetables': 'Zusätzliches Gemüse',
    
    // Vegetable names
    'veg_egg': 'Ei',
    'veg_cilantro': 'Koriander',
    'veg_basil': 'Basilikum',
    'veg_bean_sprouts': 'Sojasprossen',
    'veg_red_onion': 'Rote Zwiebel',
    'veg_corn': 'Mais',
    'veg_green_beans': 'Grüne Bohnen',
    'veg_carrot': 'Karotte',
    'veg_peanut': 'Erdnuss',
    'veg_broccoli': 'Brokkoli',
    'veg_scallion': 'Frühlingszwiebel',
    'veg_mushroom': 'Pilze',
    'veg_pepper': 'Paprika',

    // Enhanced protein translations
    'protein_chicken': 'Hähnchen',
    'protein_beef': 'Rindfleisch',
    'protein_shrimp': 'Garnelen',
    'protein_chicken_desc': 'Frische und zarte Hähnchenbrust',
    'protein_beef_desc': 'Zartes Premium-Rindfleisch',
    'protein_shrimp_desc': 'Frische Meeresgarnelen',
    'protein_chicken_beef': 'Hähnchen & Rindfleisch',
    'protein_chicken_shrimp': 'Hähnchen & Garnelen',
    'protein_beef_shrimp': 'Rindfleisch & Garnelen',
    'protein_chicken_beef_shrimp': 'Hähnchen, Rindfleisch & Garnelen',
    'protein_chicken_beef_desc': 'Perfekte Kombination aus Hähnchen und Rindfleisch',
    'protein_chicken_shrimp_desc': 'Köstliche Mischung aus Hähnchen und Garnelen',
    'protein_beef_shrimp_desc': 'Exquisite Kombination aus Rindfleisch und Garnelen',
    'protein_chicken_beef_shrimp_desc': 'Dreifach-Protein: Hähnchen, Rindfleisch und Garnelen',

    // Enhanced sauce translations
    'sauce_classic': 'Klassisch',
    'sauce_original': 'Original',
    'sauce_teriyaki': 'Teriyaki',
    'sauce_classic_desc': 'Soja- und Austernsauce',
    'sauce_original_desc': 'Koriander, Sojasprossen, Karotte, Erdnuss, Tamarindensauce und Limette',
    'sauce_teriyaki_desc': 'Traditionelle Teriyaki-Sauce',
    
    // Entrantes translations - German
    'panko_chicken': 'Panko-Hähnchen (5 Stück)',
    'panko_chicken_desc': 'Knusprige Hähnchenstücke paniert mit japanischem Panko',
    'panko_shrimp': 'Panko-Garnelen (5 Stück)',
    'panko_shrimp_desc': 'Garnelen paniert mit knusprigem Panko',
    'chicken_skewer_1': 'Hähnchen-Spieß (1 Stück)',
    'chicken_skewer_1_desc': 'Marinierter gegrillter Hähnchen-Spieß',
    'chicken_skewer_2': 'Hähnchen-Spieß (2 Stück)',
    'chicken_skewer_2_desc': 'Zwei marinierte gegrillte Hähnchen-Spieße',
    'shrimp_skewer_1': 'Garnelen-Spieß (1 Stück)',
    'shrimp_skewer_1_desc': 'Frischer gegrillter Garnelen-Spieß',
    'shrimp_skewer_2': 'Garnelen-Spieß (2 Stück)',
    'shrimp_skewer_2_desc': 'Zwei frische gegrillte Garnelen-Spieße',
    'mushroom_skewer_1': 'Pilz-Spieß (1 Stück)',
    'mushroom_skewer_1_desc': 'Frischer gegrillter Pilz-Spieß',
    'mushroom_skewer_2': 'Pilz-Spieß (2 Stück)',
    'mushroom_skewer_2_desc': 'Zwei frische gegrillte Pilz-Spieße',
    'grilled_salmon': 'Gegrillter Lachs',
    'grilled_salmon_desc': 'Frisches gegrilltes Lachsfilet',
    'spring_rolls': 'Frühlingsrollen (2 Stück)',
    'spring_rolls_desc': 'Knusprige Rollen gefüllt mit frischem Gemüse',
    'shrimp_rolls': 'Garnelen-Rollen (8 Stück)',
    'shrimp_rolls_desc': 'Knusprige Rollen gefüllt mit frischen Garnelen',
    'chicken_wings': 'Flügel (6 Stück)',
    'chicken_wings_desc': 'Marinierte und gewürzte Hähnchenflügel',
    'gyoza_fried': 'Frittierte Garnelen-Gyoza (6 Stück)',
    'gyoza_fried_desc': 'Japanische Teigtaschen gefüllt mit Garnelen, frittiert',
    'gyoza_grilled': 'Gegrillte Garnelen-Gyoza (6 Stück)',
    'gyoza_grilled_desc': 'Japanische Teigtaschen gefüllt mit Garnelen, gegrillt',
    'bao_chicken': 'Hähnchen-Bao (2 Stück)',
    'bao_chicken_desc': 'Asiatisches gedämpftes Brötchen gefüllt mit zartem Hähnchen',
    'bao_shrimp': 'Garnelen-Bao (2 Stück)',
    'bao_shrimp_desc': 'Asiatisches gedämpftes Brötchen gefüllt mit frischen Garnelen',
    'edamame': 'Edamame',
    'edamame_desc': 'Gekochte Sojabohnenhülsen mit Meersalz',
    'edamame_spicy': 'Scharfe Edamame',
    'edamame_spicy_desc': 'Gekochte Sojabohnenhülsen mit scharfen Gewürzen',

    // Soup Customizer
    'soup_customizer_title': 'Passen Sie Ihre Suppe an',
    'soup_customizer_description': 'Wählen Sie Ihre Lieblingssuppe und Ihr Protein',
    'step_soup_type': 'Wählen Sie Ihre Suppenart',
    'soup_type': 'Suppenart',
    'soup_miso': 'Miso-Suppe',
    'soup_miso_desc': 'Tofu, Wakame, Frühlingszwiebel und Meeresfrüchtesauce',
    'soup_tom_yam': 'Tom Yam-Suppe',
    'soup_tom_yam_desc': 'Pilze, Karotte, Brokkoli, Kirschtomaten, Meeresfrüchtesauce, mittelscharf',
    'custom_soup_with': 'Individuelle Suppe mit',
    'custom_soup_desc': 'und Ihren Lieblingszutaten',
    'prawn': 'Garnele',
    'veggie': 'Vegetarisch',

    // Poke customizer
    'poke_customizer_title': 'Passen Sie Ihr Poke an',
    'poke_customizer_description': 'Wählen Sie Ihre Lieblings-Poke-Bowl mit frischen Zutaten',
    'step_poke_type': 'Poke-Typ',
    'choose_your_poke': 'Wählen Sie Ihr bevorzugtes Poke',
    'poke_type': 'Poke-Typ',
    'selected': 'Ausgewählt',

    // Poke products
    'poke_korean_name': 'Koreanisches Poke',
    'poke_korean_desc': 'Japanische Reisbasis mit Sojasauce, Crispy Hähnchen, Kimchi, Kiwi, Tofu, Garnelen, Algen, gebratene Zwiebeln, Sesam, Sojasauce und Kimchi-Sauce',
    'poke_japanese_name': 'Japanisches Poke',
    'poke_japanese_desc': 'Japanische Reisbasis mit Sojasauce, Wakame, Avocado, Sesam, Kirschtomaten, Kiwi, Lachs, Garnelen, japanische Sauce und Sojasauce',
    'poke_indonesia_name': 'Indonesisches Poke',
    'poke_indonesia_desc': 'Japanische Reisbasis mit Sojasauce, Avocado, Sesam, Mango, Ananas, Kiwi, Kirschtomaten, Gurke, Sojasauce und Fruchtsauce',
    'poke_thailand_name': 'Thailand Poke',
    'poke_thailand_desc': 'Japanische Reisbasis mit Sojasauce, Avocado, Ananas, Kiwi, Garnelen, Sesam, gebratene Zwiebeln, Hähnchen, Pfeffersauce und Fruchtsauce',
    'poke_basic_name': 'Basic Poke',
    'poke_basic_desc': 'Nach Wahl: 150g Hähnchen oder 2 Crispy Hähnchen, Sesam und 3 Gemüse/Früchte aus (Wakame, Kimchi, Tofu, Algen, Gurke, Avocado, Kiwi, Kirschtomaten, Ananas, Erdbeere, Mango), plus eine Sauce (Kimchi, Soja, Rosa, Frucht, Japanisch, Caesar, Süß-Sauer)',
    'poke_premium_name': 'Premium Poke',
    'poke_premium_desc': 'Nach Wahl: 100g Lachs oder 150g Hähnchen oder 2 Crispy Hähnchen, Sesam und Garnelen, plus 4 Gemüse/Früchte aus (Wakame, Kimchi, Tofu, Algen, Gurke, Avocado, Kiwi, Kirschtomaten, Ananas, Erdbeere, Mango), plus eine Sauce (Kimchi, Soja, Rosa, Frucht, Japanisch, Caesar, Süß-Sauer)',
    
    // Salad Customizer
    'salad_customizer_title': 'PASSEN SIE IHREN SALAT AN',
    'salad_customizer_description': 'Wählen Sie Ihren Lieblingssalat und bevorzugtes Protein',
    'step_salad_type': 'Salattyp',
    'salad_type': 'Salattyp',
    
    // Salad types
    'salad_cesar': 'Caesar-Salat',
    'salad_cesar_ingredients': 'Salat, Parmesan, Avocado, Kirschtomaten, Croutons, Vinaigrette und Caesar-Sauce',
    'salad_classic_name': 'Klassischer Salat',
    'salad_classic_ingredients': 'Salat, Parmesan, Avocado, Kirschtomaten, Gurke, rote Zwiebel, Croutons, Vinaigrette und Caesar-Sauce',
     'salad_malaysia': 'Malaysia-Salat',
    'salad_malaysia_ingredients': 'Salat, Gurke, Croutons, Kirschtomaten, Walnüsse, Caesar- und Vinaigrette-Sauce und Wok-Gemüse',
    'salad_thai': 'Thailändischer Salat',
    'salad_thai_ingredients': 'Salat, Kirschtomaten, Erdnuss, Chili, Gurke, Minze, Basilikum, Vinaigrette und Caesar-Sauce, Wok-Rindfleisch',
    'salad_crispy': 'Crispy-Salat',
    'salad_crispy_ingredients': 'Salat, Karotten, Sojasprossen, Kirschtomaten, Vinaigrette und scharfe rosa Sauce, Panko Hähnchen oder Garnelen nach Wahl',
    'salad_fruit': 'Obstsalat',
    'salad_fruit_ingredients': 'Salat, Avocado, Kirschtomaten, Mango, Kiwi, Erdbeere und Fruchtsauce',
    
    // Otras del Mundo
    'otras_title': 'WELTGERICHTE',
    'otras_description': 'Spezielle Gerichte aus den Küchen der Welt',
    
    // Salad protein options
    'salad_protein_none': 'Ohne Protein',
    'salad_protein_none_desc': 'Nur Salatzutaten',
    'salad_protein_chicken': 'Hähnchen hinzufügen',
    'salad_protein_chicken_desc': 'Salat mit zartem Hähnchen',
    'salad_protein_shrimp': 'Garnelen hinzufügen',
    'salad_protein_shrimp_desc': 'Salat mit frischen Garnelen',
    'salad_protein_both': 'Hähnchen und Garnelen',
    'salad_protein_both_desc': 'Salat mit Hähnchen und Garnelen',
    
    // Drinks Products
    'drink_1': 'Coca Cola',
    'drink_1_desc': 'Coca Cola 0,33L',
    'drink_2': 'Coca Cola Zero',
    'drink_2_desc': 'Coca Cola Zero 0,33L',
    'drink_3': 'Fanta Orange',
    'drink_3_desc': 'Fanta Orange 0,33L',
    'drink_4': 'Fanta Zitrone',
    'drink_4_desc': 'Fanta Zitrone 0,33L',
    'drink_5': 'Nestea Zitrone',
    'drink_5_desc': 'Nestea Zitrone 0,33L',
    'drink_6': 'Nestea Maracuja',
    'drink_6_desc': 'Nestea Maracuja 0,33L',
    'drink_7': 'Aquarius Zitrone',
    'drink_7_desc': 'Aquarius Zitrone 0,33L',
    'drink_8': 'Aquarius Orange',
    'drink_8_desc': 'Aquarius Orange 0,33L',
    'drink_9': 'Sprite',
    'drink_9_desc': 'Sprite 0,33L',
    'drink_10': 'Wasser',
    'drink_10_desc': 'Wasser 0,33L',
    'drink_11': 'Sprudelwasser',
    'drink_11_desc': 'Sprudelwasser 0,33L',
    'drink_12': 'Apfelsaft',
    'drink_12_desc': 'Apfelsaft 0,200L',
    'drink_13': 'Ananassaft',
    'drink_13_desc': 'Ananassaft 0,200L',
    'drink_14': 'Orangensaft',
    'drink_14_desc': 'Orangensaft 0,200L',
    'drink_15': 'Pfirsichsaft',
    'drink_15_desc': 'Pfirsichsaft 0,200L',
    'drink_16': 'Tomatensaft',
    'drink_16_desc': 'Tomatensaft 0,200L',
    'drink_17': 'Shinga Bier',
    'drink_17_desc': 'Shinga Bier 1/3',
    'drink_18': 'Kirin Bier',
    'drink_18_desc': 'Kirin Bier 1/3',
    'drink_19': 'San Miguel Spezial Bier',
    'drink_19_desc': 'San Miguel Spezial Bier 1/3',
    'drink_20': 'San Miguel Glutenfrei Bier',
    'drink_20_desc': 'San Miguel Glutenfrei Bier 1/3',
    'drink_21': 'San Miguel 0.0 Bier',
    'drink_21_desc': 'San Miguel 0.0 Alkoholfrei Bier 1/3',
    'drink_22': 'Alhambra Spezial Bier',
    'drink_22_desc': 'Alhambra Spezial Bier 1/3',
    'drink_23': 'Alhambra Alkoholfrei Bier',
    'drink_23_desc': 'Alhambra Alkoholfrei Bier 1/3',
    'drink_26': 'Glas Wein',
    'drink_26_desc': 'Glas Wein',
    'drink_27': 'Flasche Wein',
    'drink_27_desc': 'Flasche Wein',
     'drink_28': 'Tinto de Verano',
    'drink_28_desc': 'Tinto de Verano',

    // Zusätzliche Extras (Saucen und Ergänzungen)
    'step_extras': 'Andere Extras',
    'extras_title': 'Extra Saucen & Beilagen',
    'extras_desc': 'Fügen Sie Ihrem Gericht zusätzliche Saucen oder Beilagen hinzu',
    'extras_label': 'Extras',
    'extra_soja': 'Sojasauce',
    'extra_ostra': 'Austernsauce',
    'extra_tamarindo': 'Tamarindensauce',
    'extra_cacahuete': 'Erdnusssauce',
    'extra_teriyaki': 'Teriyaki-Sauce',
    'extra_agridulce': 'Süß-Sauer-Sauce',
    'extra_siracha': 'Sriracha (Scharf)',
    'extra_vinagreta': 'Vinaigrette',
    'extra_cesar': 'Caesar-Sauce',
    'extra_rosa': 'Rosa Sauce',
    'extra_fruta': 'Fruchtsauce',
    'extra_mayonesa': 'Mayonnaise',
    'extra_ketchup': 'Ketchup',
    'extra_arroz_vapor': 'Extra Dampfreis',
    'extra_arroz_frito_huevo': 'Extra Gebratener Reis mit Ei',
    'extra_arroz_curry_pina': 'Extra Reis mit Curry & Ananas',
    'extra_arroz_japones': 'Extra Japanischer Reis',
    'extra_fruta_variada': 'Extra Obst-Mix Mittel',
    'extra_mochi': 'Extra Mochi',
    'extra_noodles_frito_huevo': 'Extra Gebratene Nudeln mit Ei',
    'extra_patatas_fritas': 'Extra Pommes Frites'
  },

  ru: {
    // Header
    'cart': 'Корзина',
    'phone': '951 40 19 37',
    'address': 'Plaza de la Solidaridad, 9 - Málaga',
    
    // Hero
    'prepare_to_taste': 'ПРИГОТОВЬТЕ',
    'to_your_liking': 'ПО ВАШЕМУ ВКУСУ',
    'choose_what_you_like': 'Выберите то, что вам больше нравится и...',
    'take_it_home': 'заберите домой!',
    'order_online': 'ЗАКАЗАТЬ ОНЛАЙН',
    'call_us': 'ПОЗВОНИТЬ: 951 40 19 37',
    
    // Auth
    'auth_title': 'Вход в Thaii Express',
    'login': 'Войти',
    'signup': 'Регистрация',
    'email': 'Электронная почта',
    'password': 'Пароль',
    'loading': 'Загрузка...',
    'login_success': 'Вход выполнен!',
    'signup_success': 'Аккаунт создан!',
    'check_email_confirmation': 'Пожалуйста, проверьте почту для подтверждения аккаунта.',
    'logout': 'Выйти',
    'myOrders': 'Мои заказы',
    
    // Main Categories
    'entrantes': 'Закуски',
    'arroz': 'Рис',
    'tallarines': 'Лапша',
    'sopas': 'Супы',
    'pokes': 'Поке',
    'postres': 'Десерты',
    'ensaladas': 'Салаты',
    'otras': 'Блюда мира',
    'bebidas': 'Напитки',
    
    // Proteins
    'chicken': 'Курица',
    'beef': 'Говядина',
    'pork': 'Свинина',
    'shrimp': 'Креветки',
    'vegetables': 'Овощи',
    'select_protein': 'Выберите белок',
    'protein_tab': 'Белок',
    
    // Sauces
    'teriyaki': 'Терияки',
    'sweet_sour': 'Кисло-сладкий',
    'curry_sauce': 'Карри',
    'soy_sauce': 'Соевый соус',
    'spicy_sauce': 'Острый',
    'select_sauce': 'Выберите соус',
    'sauce_tab': 'Соус',
    'spicy_level': 'Уровень остроты',
    
    // Rice Customizer
    'rice_customizer_title': 'Настройте свой рис',
    'rice_customizer_description': 'Выберите любимый белок и соус для создания идеального блюда',
    'customize_rice': 'Настроить рис',
    'selected_items': 'Выбранные элементы',
    
    // Subcategories
    'classic': 'Классический',
    'yellow_curry': 'Жёлтое карри',
    'green_curry': 'Зелёное карри',
    'red_curry': 'Красное карри',
    
    // Common
    'price': 'Цена',
    'add_to_cart': 'В корзину',
    'vegetarian': 'Вегетарианское',
    'spicy': 'Острое',
    
    // Cart
    'your_cart': 'Ваша корзина',
    'empty_cart': 'Ваша корзина пуста',
    'quantity': 'Количество',
    'remove': 'Удалить',
    'subtotal': 'Подитог',
    'delivery_fee': 'Стоимость доставки',
    'total': 'Итого',
    'customer_info': 'Информация о клиенте',
    'name': 'Имя',
    'phone_number': 'Телефон',
    'address_full': 'Полный адрес',
    'notes': 'Примечания (необязательно)',
    'send_order_whatsapp': 'ОТПРАВИТЬ ЗАКАЗ ЧЕРЕЗ WHATSAPP',
    
    // Dialog
    'doubts_about_dishes': 'Есть вопросы о наших блюдах?',
    'khopi_greeting': 'Привет! Я Копи, маскот Thaii Express. Если у вас есть вопросы об ингредиентах или нужна помощь с выбором — позвоните нам!',
    'see_full_menu': 'ПОЛНОЕ МЕНЮ',
    
    // Footer
    'restaurant_description': 'Аутентичная азиатская еда на вынос. Приготовьте по своему вкусу и заберите домой.',
    'contact_title': 'КОНТАКТЫ',
    'hours_title': 'ЧАСЫ РАБОТЫ',
    'monday_sunday': 'Понедельник - Воскресенье',
    'hours_time': '12:00 - 23:00',
    'online_orders_available': 'Онлайн-заказы доступны в течение всего времени работы',
    'all_rights_reserved': '© 2024 Thaii Express Málaga. Все права защищены.',
    'top_sales': 'Хиты продаж',
    
    // Loading and Error states
    'loading_products': 'Загрузка продуктов...',
    'error_loading': 'Ошибка',
    'retry': 'Повторить',
    'coming_soon': 'Скоро будет доступно...',
    
    // Category descriptions
    'starters_description': 'Вкусные закуски для начала кулинарного путешествия',
    'noodles_description': 'Традиционная азиатская лапша, обжаренная со свежими овощами',
    'soups_description': 'Согревающие супы с подлинными азиатскими вкусами',
    'pokes_description': 'Свежие и полезные поке с качественными ингредиентами',
    'desserts_description': 'Вкуснейшие десерты для сладкого завершения',
    'salads_description': 'Свежие и питательные салаты с сезонными ингредиентами',
    'drinks_description': 'Освежающие напитки к вашему блюду',
    
    // Rice Customizer Proteins
    'chicken_protein': 'Курица',
    'beef_protein': 'Говядина',
    'shrimp_protein': 'Креветки',
    'chicken_beef': 'Курица и говядина',
    'chicken_shrimp': 'Курица и креветки',
    'beef_shrimp': 'Говядина и креветки',
    'mix_three': 'Курица, говядина и креветки',
    
    // Rice Customizer Protein Descriptions
    'chicken_desc': 'Нежная маринованная курица',
    'beef_desc': 'Сочная обжаренная говядина',
    'shrimp_desc': 'Свежие морские креветки',
    'chicken_beef_desc': 'Сочетание курицы и говядины',
    'chicken_shrimp_desc': 'Курица со свежими креветками',
    'beef_shrimp_desc': 'Говядина с морскими креветками',
    'mix_three_desc': 'Полное сочетание белков',
    
    // Rice Customizer Sauces
    'classic_sauce': 'Классический соус',
    'original_sauce': 'Оригинальный соус',
    'teriyaki_sauce': 'Соус Терияки',
    'yellow_curry_sauce': 'Жёлтое карри',
    'green_curry_sauce': 'Зелёное карри',
    'red_curry_sauce': 'Красное карри',
    
    // Rice Customizer Sauce Descriptions
    'classic_sauce_desc': 'Традиционный азиатский соус',
    'original_sauce_desc': 'Наш фирменный рецепт',
    'teriyaki_sauce_desc': 'Сладкий и пикантный японский соус',
    'yellow_curry_sauce_desc': 'Мягкое жёлтое карри',
    'green_curry_sauce_desc': 'Средне-острое зелёное карри',
    'red_curry_sauce_desc': 'Интенсивное острое красное карри',
    
    // Spicy levels
    'medium_spicy': 'Средняя острота',
    'spicy_level_high': 'Острое',
    
    // Custom rice creation
    'custom_rice_with': 'Жареный рис с',
    'custom_rice_and': 'и',
    'custom_rice_desc': 'Жареный рис по вашему выбору с',

    // Noodle types
    'noodle_finos': 'Тонкая (Нудлс)',
    'noodle_anchos': 'Широкая (Пад Тай)',
    'noodle_glass': 'Стеклянная',
    'noodle_udon': 'Удон',
    'noodle_finos_desc': 'Традиционная тонкая лапша',
    'noodle_anchos_desc': 'Широкая лапша в стиле Пад Тай',
    'noodle_glass_desc': 'Прозрачная бобовая лапша',
    'noodle_udon_desc': 'Толстая японская лапша',

    // Noodle customizer
    'noodle_customizer_title': 'НАСТРОЙТЕ СВОЮ ЛАПШУ',
    'noodle_customizer_description': 'Выберите тип лапши, любимый белок и идеальный соус',
    'step_noodle_type': 'Тип лапши',
    'step_protein': 'Белок',
    'step_sauce': 'Соус',
    'noodle_type': 'Тип лапши',
    'custom_noodles_with': 'Лапша по выбору с',
    'custom_noodles_and': 'и',
    'custom_noodles_desc': 'Лапша, обжаренная в воке с',
    'custom_noodles_with_sauce': 'с соусом',
    'order_summary': 'Сводка заказа',
    'protein': 'Белок',
    'sauce': 'Соус',
    
    // Extra vegetables
    'extra_vegetables': 'Дополнительные овощи',
    'extra_vegetables_optional': 'Дополнительные овощи (по желанию)',
    'extra_vegetables_desc': 'Выберите дополнительные овощи для вашего блюда',
    'extra_vegetables_label': 'Доп. овощи',
    'step_vegetables': 'Доп. овощи',
    
    // Vegetable names
    'veg_egg': 'Яйцо',
    'veg_cilantro': 'Кинза',
    'veg_basil': 'Базилик',
    'veg_bean_sprouts': 'Ростки сои',
    'veg_red_onion': 'Красный лук',
    'veg_corn': 'Кукуруза',
    'veg_green_beans': 'Стручковая фасоль',
    'veg_carrot': 'Морковь',
    'veg_peanut': 'Арахис',
    'veg_broccoli': 'Брокколи',
    'veg_scallion': 'Зелёный лук',
    'veg_mushroom': 'Грибы',
    'veg_pepper': 'Перец',

    // Enhanced protein translations
    'protein_chicken': 'Курица',
    'protein_beef': 'Говядина',
    'protein_shrimp': 'Креветки',
    'protein_chicken_desc': 'Свежая и нежная куриная грудка',
    'protein_beef_desc': 'Нежная говядина премиум-класса',
    'protein_shrimp_desc': 'Свежие морские креветки',
    'protein_chicken_beef': 'Курица и говядина',
    'protein_chicken_shrimp': 'Курица и креветки',
    'protein_beef_shrimp': 'Говядина и креветки',
    'protein_chicken_beef_shrimp': 'Курица, говядина и креветки',
    'protein_chicken_beef_desc': 'Идеальное сочетание курицы и говядины',
    'protein_chicken_shrimp_desc': 'Вкусное сочетание курицы и креветок',
    'protein_beef_shrimp_desc': 'Изысканное сочетание говядины и креветок',
    'protein_chicken_beef_shrimp_desc': 'Тройной белок: курица, говядина и креветки',

    // Enhanced sauce translations
    'sauce_classic': 'Классический',
    'sauce_original': 'Оригинальный',
    'sauce_teriyaki': 'Терияки',
    'sauce_classic_desc': 'Соевый и устричный соус',
    'sauce_original_desc': 'Кинза, ростки сои, морковь, арахис, соус тамаринд и лайм',
    'sauce_teriyaki_desc': 'Традиционный соус терияки',
    
    // Entrantes translations - Russian
    'panko_chicken': 'Панко курица (5 шт.)',
    'panko_chicken_desc': 'Хрустящие кусочки курицы в японской панировке панко',
    'panko_shrimp': 'Панко креветки (5 шт.)',
    'panko_shrimp_desc': 'Креветки в хрустящей панировке панко',
    'chicken_skewer_1': 'Шашлычок из курицы (1 шт.)',
    'chicken_skewer_1_desc': 'Маринованный куриный шашлычок на гриле',
    'chicken_skewer_2': 'Шашлычок из курицы (2 шт.)',
    'chicken_skewer_2_desc': 'Два маринованных куриных шашлычка на гриле',
    'shrimp_skewer_1': 'Шашлычок из креветок (1 шт.)',
    'shrimp_skewer_1_desc': 'Свежий шашлычок из креветок на гриле',
    'shrimp_skewer_2': 'Шашлычок из креветок (2 шт.)',
    'shrimp_skewer_2_desc': 'Два свежих шашлычка из креветок на гриле',
    'mushroom_skewer_1': 'Шашлычок из грибов (1 шт.)',
    'mushroom_skewer_1_desc': 'Свежий грибной шашлычок на гриле',
    'mushroom_skewer_2': 'Шашлычок из грибов (2 шт.)',
    'mushroom_skewer_2_desc': 'Два свежих грибных шашлычка на гриле',
    'grilled_salmon': 'Лосось на гриле',
    'grilled_salmon_desc': 'Свежее филе лосося на гриле',
    'spring_rolls': 'Спринг-роллы (2 шт.)',
    'spring_rolls_desc': 'Хрустящие роллы со свежими овощами',
    'shrimp_rolls': 'Роллы с креветками (8 шт.)',
    'shrimp_rolls_desc': 'Хрустящие роллы со свежими креветками',
    'chicken_wings': 'Крылышки (6 шт.)',
    'chicken_wings_desc': 'Маринованные куриные крылышки со специями',
    'gyoza_fried': 'Гёдза с креветками жареные (6 шт.)',
    'gyoza_fried_desc': 'Японские пельмени с начинкой из креветок, жареные',
    'gyoza_grilled': 'Гёдза с креветками на гриле (6 шт.)',
    'gyoza_grilled_desc': 'Японские пельмени с начинкой из креветок, на гриле',
    'bao_chicken': 'Бао с курицей (2 шт.)',
    'bao_chicken_desc': 'Азиатская паровая булочка с нежной курицей',
    'bao_shrimp': 'Бао с креветками (2 шт.)',
    'bao_shrimp_desc': 'Азиатская паровая булочка со свежими креветками',
    'edamame': 'Эдамамэ',
    'edamame_desc': 'Отварные стручки сои с морской солью',
    'edamame_spicy': 'Эдамамэ острые',
    'edamame_spicy_desc': 'Отварные стручки сои с острыми специями',

    // Soup Customizer
    'soup_customizer_title': 'Настройте свой суп',
    'soup_customizer_description': 'Выберите любимый тип супа и белок',
    'step_soup_type': 'Выберите тип супа',
    'soup_type': 'Тип супа',
    'soup_miso': 'Суп Мисо',
    'soup_miso_desc': 'Тофу, вакаме, зелёный лук и соус из морепродуктов',
    'soup_tom_yam': 'Суп Том Ям',
    'soup_tom_yam_desc': 'Грибы, морковь, брокколи, помидоры черри, соус из морепродуктов, средне-острый',
    'custom_soup_with': 'Суп по выбору с',
    'custom_soup_desc': 'и вашими любимыми ингредиентами',
    'prawn': 'Лангустин',
    'veggie': 'Вегетарианский',

    // Poke customizer
    'poke_customizer_title': 'Настройте свой Поке',
    'poke_customizer_description': 'Выберите любимый поке-боул со свежими ингредиентами',
    'step_poke_type': 'Тип Поке',
    'choose_your_poke': 'Выберите предпочитаемый поке',
    'poke_type': 'Тип Поке',
    'selected': 'Выбрано',

    // Poke products
    'poke_korean_name': 'Корейский Поке',
    'poke_korean_desc': 'Рисовая база с соевым соусом, хрустящая курица, кимчи, киви, тофу, креветки, водоросли, жареный лук, кунжут, соевый соус и соус кимчи',
    'poke_japanese_name': 'Японский Поке',
    'poke_japanese_desc': 'Рисовая база с соевым соусом, вакаме, авокадо, кунжут, помидоры черри, киви, лосось, креветки, японский соус и соевый соус',
    'poke_indonesia_name': 'Индонезийский Поке',
    'poke_indonesia_desc': 'Рисовая база с соевым соусом, авокадо, кунжут, манго, ананас, киви, помидоры черри, огурец, соевый соус и фруктовый соус',
    'poke_thailand_name': 'Тайский Поке',
    'poke_thailand_desc': 'Рисовая база с соевым соусом, авокадо, ананас, киви, креветки, кунжут, жареный лук, курица, перечный соус и фруктовый соус',
    'poke_basic_name': 'Базовый Поке',
    'poke_basic_desc': 'На выбор: 150г курицы или 2 хрустящих курицы, кунжут и 3 овоща/фрукта из (вакаме, кимчи, тофу, водоросли, огурец, авокадо, киви, помидоры черри, ананас, клубника, манго), плюс один соус (Кимчи, соевый, Розовый, фруктовый, Японский, Цезарь, кисло-сладкий)',
    'poke_premium_name': 'Премиум Поке',
    'poke_premium_desc': 'На выбор: 100г лосося или 150г курицы или 2 хрустящих курицы, кунжут и креветки, плюс 4 овоща/фрукта из (вакаме, кимчи, тофу, водоросли, огурец, авокадо, киви, помидоры черри, ананас, клубника, манго), плюс один соус (Кимчи, соевый, Розовый, фруктовый, Японский, Цезарь, кисло-сладкий)',
    
    // Salad Customizer
    'salad_customizer_title': 'НАСТРОЙТЕ СВОЙ САЛАТ',
    'salad_customizer_description': 'Выберите любимый салат и предпочитаемый белок',
    'step_salad_type': 'Тип салата',
    'salad_type': 'Тип салата',
    
    // Salad types
    'salad_cesar': 'Салат Цезарь',
    'salad_cesar_ingredients': 'Салат, пармезан, авокадо, помидоры, крутоны, винегрет и соус Цезарь',
    'salad_classic_name': 'Классический салат',
    'salad_classic_ingredients': 'Салат, пармезан, авокадо, помидоры черри, огурец, красный лук, крутоны, винегрет и соус Цезарь',
    'salad_malaysia': 'Салат Малайзия',
    'salad_malaysia_ingredients': 'Салат, огурец, крутоны, помидоры черри, орехи, соус Цезарь и винегрет, овощи вок',
    'salad_thai': 'Тайский салат',
    'salad_thai_ingredients': 'Салат, помидоры черри, арахис, чили, огурец, мята, базилик, винегрет и соус Цезарь, говядина вок',
    'salad_crispy': 'Хрустящий салат',
    'salad_crispy_ingredients': 'Салат, морковь, ростки сои, помидоры черри, винегрет и острый розовый соус, панко курица или креветки на выбор',
    'salad_fruit': 'Фруктовый салат',
    'salad_fruit_ingredients': 'Салат, авокадо, помидоры черри, манго, киви, клубника и фруктовый соус',
    
    // Otras del Mundo
    'otras_title': 'БЛЮДА МИРА',
    'otras_description': 'Особые блюда из кухонь мира',
    
    // Salad protein options
    'salad_protein_none': 'Без белка',
    'salad_protein_none_desc': 'Только ингредиенты салата',
    'salad_protein_chicken': 'Добавить курицу',
    'salad_protein_chicken_desc': 'Салат с нежной курицей',
    'salad_protein_shrimp': 'Добавить креветки',
    'salad_protein_shrimp_desc': 'Салат со свежими креветками',
    'salad_protein_both': 'Курица и креветки',
    'salad_protein_both_desc': 'Салат с курицей и креветками',
    
    // Drinks Products
    'drink_1': 'Кока-Кола',
    'drink_1_desc': 'Кока-Кола 0,33л',
    'drink_2': 'Кока-Кола Зеро',
    'drink_2_desc': 'Кока-Кола Зеро 0,33л',
    'drink_3': 'Фанта Апельсин',
    'drink_3_desc': 'Фанта Апельсин 0,33л',
    'drink_4': 'Фанта Лимон',
    'drink_4_desc': 'Фанта Лимон 0,33л',
    'drink_5': 'Нести Лимон',
    'drink_5_desc': 'Нести Лимон 0,33л',
    'drink_6': 'Нести Маракуйя',
    'drink_6_desc': 'Нести Маракуйя 0,33л',
    'drink_7': 'Аквариус Лимон',
    'drink_7_desc': 'Аквариус Лимон 0,33л',
    'drink_8': 'Аквариус Апельсин',
    'drink_8_desc': 'Аквариус Апельсин 0,33л',
    'drink_9': 'Спрайт',
    'drink_9_desc': 'Спрайт 0,33л',
    'drink_10': 'Вода',
    'drink_10_desc': 'Вода 0,33л',
    'drink_11': 'Газированная вода',
    'drink_11_desc': 'Газированная вода 0,33л',
    'drink_12': 'Яблочный сок',
    'drink_12_desc': 'Яблочный сок 0,200л',
    'drink_13': 'Ананасовый сок',
    'drink_13_desc': 'Ананасовый сок 0,200л',
    'drink_14': 'Апельсиновый сок',
    'drink_14_desc': 'Апельсиновый сок 0,200л',
    'drink_15': 'Персиковый сок',
    'drink_15_desc': 'Персиковый сок 0,200л',
    'drink_16': 'Томатный сок',
    'drink_16_desc': 'Томатный сок 0,200л',
    'drink_17': 'Пиво Shinga',
    'drink_17_desc': 'Пиво Shinga 1/3',
    'drink_18': 'Пиво Kirin',
    'drink_18_desc': 'Пиво Kirin 1/3',
    'drink_19': 'Пиво San Miguel Especial',
    'drink_19_desc': 'Пиво San Miguel Especial 1/3',
    'drink_20': 'Пиво San Miguel без глютена',
    'drink_20_desc': 'Пиво San Miguel без глютена 1/3',
    'drink_21': 'Пиво San Miguel 0.0',
    'drink_21_desc': 'Пиво San Miguel 0.0 безалкогольное 1/3',
    'drink_22': 'Пиво Alhambra Especial',
    'drink_22_desc': 'Пиво Alhambra Especial 1/3',
    'drink_23': 'Пиво Alhambra безалкогольное',
    'drink_23_desc': 'Пиво Alhambra безалкогольное 1/3',
    'drink_26': 'Бокал вина',
    'drink_26_desc': 'Бокал вина',
    'drink_27': 'Бутылка вина',
    'drink_27_desc': 'Бутылка вина',
    'drink_28': 'Тинто де Верано',
    'drink_28_desc': 'Тинто де Верано',

    // Дополнительные экстра (соусы и дополнения)
    'step_extras': 'Другие допол.',
    'extras_title': 'Дополнительные соусы и гарниры',
    'extras_desc': 'Добавьте дополнительные соусы или гарниры к вашему блюду',
    'extras_label': 'Дополнения',
    'extra_soja': 'Соевый соус',
    'extra_ostra': 'Устричный соус',
    'extra_tamarindo': 'Соус тамаринд',
    'extra_cacahuete': 'Арахисовый соус',
    'extra_teriyaki': 'Соус Терияки',
    'extra_agridulce': 'Кисло-сладкий соус',
    'extra_siracha': 'Шрирача (острый)',
    'extra_vinagreta': 'Винегрет',
    'extra_cesar': 'Соус Цезарь',
    'extra_rosa': 'Розовый соус',
    'extra_fruta': 'Фруктовый соус',
    'extra_mayonesa': 'Майонез',
    'extra_ketchup': 'Кетчуп',
    'extra_arroz_vapor': 'Доп. рис на пару',
    'extra_arroz_frito_huevo': 'Доп. жареный рис с яйцом',
    'extra_arroz_curry_pina': 'Доп. рис с карри и ананасом',
    'extra_arroz_japones': 'Доп. японский рис',
    'extra_fruta_variada': 'Доп. фруктовый микс',
    'extra_mochi': 'Доп. моти',
    'extra_noodles_frito_huevo': 'Доп. жареная лапша с яйцом',
    'extra_patatas_fritas': 'Доп. картофель фри'
  }
};