// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqqffccvnpnmdoqowdlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxcWZmY2N2bnBubWRvcW93ZGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTU0OTQsImV4cCI6MjA3MjI3MTQ5NH0.yROAT6LwzJHjNvb5Rpj7-e37NYcpyXRe7KcANewAgPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});